/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LanguageConfig, SupportedLanguage } from "./types";

export const LANGUAGES: LanguageConfig[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    tagline: "Your Farming Friend",
    langSelector: "Choose Language",
    cropScan: "Crop Scan",
    voiceProblem: "Voice Query",
    weather: "Weather",
    experts: "Ag Experts",
    shops: "Agri Shops",
    scanHeading: "Scan Crop Problem",
    scanSub: "Upload or take a photo of your crop to instantly diagnose diseases or nutrient deficiencies",
    takePhoto: "Take Photo",
    uploadPhoto: "Upload Photo",
    sampleDiseases: "Test with Sample Crop Diseases",
    analyzing: "Analyzing with Gemini AI...",
    results: "Diagnostic Report",
    confidence: "Confidence Level",
    symptoms: "Symptoms Observed",
    treatment: "Immediate Treatment Plan",
    prevention: "Long-term Prevention Advice",
    voiceTitle: "Speak Your Farming Problem",
    voiceSub: "Hold the microphone, state your crop issue in your local language, and hear the solution read aloud",
    recordStart: "Tap to record & speak",
    recording: "Recording... Tap again to solve",
    converting: "Transcribing and solving with Gemini...",
    playSolution: "Listen to Solution",
    orText: "Or type your problem",
    askButton: "Ask Mitra",
    weatherTitle: "Weather Agricultural suggestions",
    weatherSub: "Weekly localized meteorological data paired with Gemini farming instructions",
    current: "Current Conditions",
    weeklyForecast: "7-Day Agri-Forecast",
    gpsLocation: "Use GPS Location",
    searchCity: "Enter City or Region",
    expertTitle: "Agriculture Experts Portal",
    expertSub: "Consult with government Krishi Vigyan Kendra officers or private agronomists",
    expertList: "Available Agronomists Nearby",
    scheduleConsult: "Schedule Appointment",
    chatExpert: "Chat with Expert",
    callExpert: "Audio/Video Call",
    bookingDate: "Select Date",
    bookingTime: "Preferred Time Slot",
    bookingNotes: "Describe your issue",
    bookButton: "Book Free Consultation",
    shopTitle: "Nearby Agri Shops & Seeds",
    shopSub: "Find seeds, certified fertilizers, crop protection shops, and nurseries near you",
    rating: "Rating",
    navigationRoute: "Show Route Map",
    contactNo: "Call Shop",
    distanceLabel: "Distance",
    helpPlaceholder: "Ex: My tomato leaves are turning brown with yellow halos, what should I do?",
    farmerBoard: "Farmer Board",
    farmerToolbelt: "Farmer Menu",
    gpsTelemetry: "GPS Telemetry",
    gpsTelemetryDesc: "KrishiMitra matches regional agronomist distance matrices and open meteorological vectors automatically.",
    namasteFriend: "Namaste Farmer Friend!",
    customDashboardSub: "Diagnose crop disease instantly, verify tailored weather alerts, consult KVK scientists, or explore seed maps in your mother tongue.",
    weatherStrategy: "Weather Strategy",
    metForecast: "Met Forecast",
    atmosphereModelsLoading: "Downloading atmospheric models...",
    spraying: "Spraying",
    watering: "Watering",
    full7DayPlan: "Full 7-Day Plan",
    pathology: "Pathology",
    instantCropScan: "Instant Crop Scan",
    bentoScanDesc: "Failing foliage? Snap or choose a preloaded crop specimen. Gemini immediately identifies pest decays with actionable treatment lists.",
    diagnosisSuite: "Diagnosis Suite",
    agriTrade: "Agri Trade",
    registeredAgriShops: "Registered Agri-Shops",
    nearby: "nearby",
    launchRoute: "Launch Navigation Route",
    agriScienceAdvisors: "Agri Science Advisors",
    certified: "Certified",
    bookedAppointments: "Booked Appointments",
    approved: "Approved",
    consultAdvisors: "Consult with state agronomists or certified farm doctors. Book direct audio/video calls or instant chats for high-quality soil reports.",
    consultExperts: "Consult Experts",
    previousDiagnostics: "Previous Diagnostics",
    advice: "advice:",
    viewForecast: "View Forecast",
    zone: "ZONE",
    indianSemiArid: "Indian Semi-Arid"
  },
  hi: {
    tagline: "आपका खेती साथी",
    langSelector: "भाषा चुनें",
    cropScan: "फसल स्कैन",
    voiceProblem: "आवाज से पूछें",
    weather: "मौसम",
    experts: "कृषि विशेषज्ञ",
    shops: "कृषि दुकानें",
    scanHeading: "फसल समस्या स्कैन करें",
    scanSub: "बीमारियों या पोषक तत्वों की कमी का तुरंत निदान करने के लिए फसल की फोटो अपलोड करें या खींचें",
    takePhoto: "फ़ोटो खींचें",
    uploadPhoto: "फ़ोटो अपलोड करें",
    sampleDiseases: "परीक्षण के लिए नमूना फसल रोग",
    analyzing: "जेमिनी एआई विश्लेषण कर रहा है...",
    results: "निदान रिपोर्ट",
    confidence: "विश्वास स्तर",
    symptoms: "दिखने वाले लक्षण",
    treatment: "तत्काल उपचार योजना",
    prevention: "दीर्घकालिक रोकथाम सलाह",
    voiceTitle: "अपनी खेती की समस्या बोलें",
    voiceSub: "माइक बटन दबाएं, स्थानीय भाषा में फसल समस्या बताएं, और समाधान बोलकर सुनाया जाएगा",
    recordStart: "रिकॉर्ड करने के लिए दबाएं",
    recording: "रिकॉर्डिंग चालू है... रोकने के लिए पुनः दबाएं",
    converting: "जेमिनी द्वारा अनुवाद और समाधान किया जा रहा है...",
    playSolution: "समाधान सुनें",
    orText: "या अपनी समस्या लिखें",
    askButton: "मित्र से पूछें",
    weatherTitle: "मौसम आधारित कृषि सलाह",
    weatherSub: "साप्ताहिक मौसम डाटा के साथ जेमिनी फसल सुरक्षा निर्देश",
    current: "वर्तमान मौसम",
    weeklyForecast: "7-दिन कृषि-पूर्वानुमान",
    gpsLocation: "जीपीएस स्थान का उपयोग करें",
    searchCity: "शहर या क्षेत्र दर्ज करें",
    expertTitle: "कृषि विशेषज्ञ पोर्टल",
    expertSub: "सरकारी कृषि विज्ञान केंद्र (KVK) अधिकारियों या निजी कृषि वैज्ञानिकों से सलाह लें",
    expertList: "आसपास उपलब्ध कृषि वैज्ञानिक",
    scheduleConsult: "मुलाकात निर्धारित करें",
    chatExpert: "विशेषज्ञ से चैट करें",
    callExpert: "ऑडियो/वीडियो कॉल",
    bookingDate: "तारीख चुनें",
    bookingTime: "पसंदीदा समय",
    bookingNotes: "अपनी समस्या का विवरण दें",
    bookButton: "निशुल्क परामर्श बुक करें",
    shopTitle: "आसपास की कृषि दुकानें",
    shopSub: "अपने निकटतम बीज, प्रमाणित खाद, कीटनाशक और नर्सरी की दुकानें खोजें",
    rating: "रेटिंग",
    navigationRoute: "मार्ग मानचित्र दिखाएं",
    contactNo: "दुकान को कॉल करें",
    distanceLabel: "दूरी",
    helpPlaceholder: "उदा: मेरे टमाटर के पत्ते पीले घेरे के साथ भूरे हो रहे हैं, मैं क्या करूँ?",
    farmerBoard: "किसान बोर्ड",
    farmerToolbelt: "किसान मेनू",
    gpsTelemetry: "जीपीएस टेलीमेट्री",
    gpsTelemetryDesc: "कृषिमित्र क्षेत्रीय कृषि वैज्ञानिक दूरी मेट्रिक्स और खुले मौसम संबंधी डेटा का स्वचालित मिलान करता है।",
    namasteFriend: "नमस्ते किसान भाई!",
    customDashboardSub: "फसल रोग का तुरंत निदान करें, मौसम अलर्ट सत्यापित करें, कृषि विज्ञान केंद्र वैज्ञानिकों से परामर्श लें, या स्थानीय भाषा में बीज दुकानों का पता लगाएं।",
    weatherStrategy: "मौसम रणनीति",
    metForecast: "मौसम पूर्वानुमान",
    atmosphereModelsLoading: "मौसम संबंधी मॉडल डाउनलोड हो रहे हैं...",
    spraying: "छिड़काव",
    watering: "सिंचाई",
    full7DayPlan: "7-दिवसीय पूर्ण योजना",
    pathology: "रोग विज्ञान",
    instantCropScan: "त्वरित फसल स्कैन",
    bentoScanDesc: "पत्तियों में खराबी? फोटो खींचें या नमूना फसल चुनें। जेमिनी तुरंत कीटों और बीमारियों की पहचान कर उपचार योजना प्रदान करेगा।",
    diagnosisSuite: "निदान सुइट",
    agriTrade: "कृषि व्यापार",
    registeredAgriShops: "पंजीकृत कृषि दुकानें",
    nearby: "पास में",
    launchRoute: "मार्ग नक्शा दिखाएं",
    agriScienceAdvisors: "कृषि वैज्ञानिक सलाहकार",
    certified: "प्रमाणित",
    bookedAppointments: "बुक की गई नियुक्तियां",
    approved: "स्वीकृत",
    consultAdvisors: "राज्य के कृषि वैज्ञानिकों या प्रमाणित फार्म डॉक्टरों से परामर्श लें। मिट्टी की उच्च गुणवत्ता वाली रिपोर्ट के लिए सीधे कॉल या चैट बुक करें।",
    consultExperts: "विशेषज्ञों से सलाह लें",
    previousDiagnostics: "पिछला निदान इतिहास",
    advice: "सलाह:",
    viewForecast: "पूर्वानुमान देखें",
    zone: "क्षेत्र",
    indianSemiArid: "अर्ध-शुष्क भारतीय क्षेत्र"
  },
  kn: {
    tagline: "ನಿಮ್ಮ ಕೃಷಿ ಗೆಳೆಯ",
    langSelector: "ಭಾಷೆ ಆರಿಸಿ",
    cropScan: "ಬೆಳೆ ಸ್ಕ್ಯಾನ್",
    voiceProblem: "ಧ್ವನಿ ಸಮಸ್ಯೆ",
    weather: "ಹವಾಮಾನ",
    experts: "ಕೃಷಿ ತಜ್ಞರು",
    shops: "ಕೃಷಿ ಅಂಗಡಿಗಳು",
    scanHeading: "ಬೆಳೆ ಸಮಸ್ಯೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    scanSub: "ರೋಗಗಳು ಅಥವಾ ಪೋಷಕಾಂಶಗಳ ಕೊರತೆಯನ್ನು ತಕ್ಷಣ ಪತ್ತೆಹಚ್ಚಲು ನಿಮ್ಮ ಬೆಳೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ತೆಗೆಯಿರಿ",
    takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    uploadPhoto: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    sampleDiseases: "ಪರೀಕ್ಷಿಸಲು ಮಾದರಿ ಬೆಳೆ ರೋಗಗಳು",
    analyzing: "ಜೆಮಿನಿ ಎಐ ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    results: "ರೋಗ ಪತ್ತೆ ವರದಿ",
    confidence: "ನಿಖರತೆಯ ಮಟ್ಟ",
    symptoms: "ಕಂಡುಬಂದ ಲಕ್ಷಣಗಳು",
    treatment: "ತಕ್ಷಣದ ಚಿಕಿತ್ಸಾ ಕ್ರಮಗಳು",
    prevention: "ದೀರ್ಘಾವಧಿಯ ತಡೆಗಟ್ಟುವ ಸಲಹೆಗಳು",
    voiceTitle: "ಕೃಷಿ ಸಮಸ್ಯೆಗಳನ್ನು ಧ್ವನಿ ಮೂಲಕ ತಿಳಿಸಿ",
    voiceSub: "ಮೈಕ್ರೊಫೋನ್ ಹಿಡಿದುಕೊಂಡು, ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ಸಮಸ್ಯೆಯನ್ನು ತಿಳಿಸಿ ಮತ್ತು ಆಡಿಯೋ ಉತ್ತರ ಆಲಿಸಿ",
    recordStart: "ರೆಕಾರ್ಡ್ ಮಾಡಲು ಒತ್ತಿ",
    recording: "ರೆಕಾರ್ಡಿಂಗ್ ಆಗುತ್ತಿದೆ... ನಿಲ್ಲಿಸಲು ಮತ್ತೆ ಒತ್ತಿ",
    converting: "ಜೆಮಿನಿ ಮೂಲಕ ಭಾಷಾಂತರ ಮತ್ತು ಪರಿಹಾರ ಚಾಲ್ತಿಯಲ್ಲಿದೆ...",
    playSolution: "ಪರಿಹಾರ ಆಲಿಸಿ",
    orText: "ಅಥವಾ ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಬರೆಯಿರಿ",
    askButton: "ಮಿತ್ರರನ್ನು ಕೇಳಿ",
    weatherTitle: "ಹವಾಮಾನ ಆಧಾರಿತ ಕೃಷಿ ಸಲಹೆಗಳು",
    weatherSub: "ವಾರದ ಹವಾಮಾನ ದತ್ತಾಂಶ ಹಾಗೂ ಜೆಮಿನಿ ಬೆಳೆ ಸಂರಕ್ಷಣೆ ಮಾರ್ಗಸೂಚಿಗಳು",
    current: "ಪ್ರಸ್ತುತ ಹವಾಮಾನ",
    weeklyForecast: "7-ದಿನಗಳ ಕೃಷಿ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    gpsLocation: "ಜಿಪಿಎಸ್ ಬಳಸಿ",
    searchCity: "ಊರು ಅಥವಾ ಜಿಲ್ಲೆ ನಮೂದಿಸಿ",
    expertTitle: "ಕೃಷಿ ತಜ್ಞರ ವೇದಿಕೆ",
    expertSub: "ಸರ್ಕಾರಿ ಕೃಷಿ ವಿಜ್ಞಾನ ಕೇಂದ್ರ (KVK) ಅಧಿಕಾರಿಗಳು ಅಥವಾ ಖಾಸಗಿ ತಜ್ಞರಿಂದ ಸಲಹೆ ಪಡೆಯಿರಿ",
    expertList: "ಸಮೀಪದ ಲಭ್ಯವಿರುವ ಕೃಷಿ ತಜ್ಞರು",
    scheduleConsult: "ಸಲಹಾ ಸಮಯ ಕಾಯ್ದಿರಿಸಿ",
    chatExpert: "ತಜ್ಞರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
    callExpert: "ಆಡಿಯೋ/ವಿಡಿಯೋ ಕರೆ",
    bookingDate: "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
    bookingTime: "ಸಮಯ ಆಯ್ಕೆಮಾಡಿ",
    bookingNotes: "ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ",
    bookButton: "ಉಚಿತ ಸಲಹೆ ಕಾಯ್ದಿರಿಸಿ",
    shopTitle: "ಹತ್ತಿರದ ಕೃಷಿ ಅಂಗಡಿಗಳು",
    shopSub: "ನಿಮ್ಮ ಹತ್ತಿರದ ಬೀಜಗಳು, ಪ್ರಮಾಣೀಕೃತ ರಸಗೊಬ್ಬರಗಳು, ಕೀಟನಾಶಕಗಳು ಮತ್ತು ನರ್ಸರಿಗಳನ್ನು ಪತ್ತೆ ಮಾಡಿ",
    rating: "ರೇಟಿಂಗ್",
    navigationRoute: "ಮಾರ್ಗ ನಕ್ಷೆ ತೋರಿಸಿ",
    contactNo: "ಅಂಗಡಿಗೆ ಕರೆ ಮಾಡಿ",
    distanceLabel: "ದೂರ",
    helpPlaceholder: "ಉದಾ: ನನ್ನ ಟೊಮೆಟೊ ಎಲೆಗಳು ಹಳದಿ ವರ್ತುಲದೊಂದಿಗೆ ಕಂದು ಬಣ್ಣಕ್ಕೆ ತಿರುಗುತ್ತಿವೆ, ಏನು ಮಾಡಬೇಕು?",
    farmerBoard: "ರೈತ ಮಂಡಳಿ",
    farmerToolbelt: "ರೈತ ಮೆನು",
    gpsTelemetry: "ಜಿಪಿಎಸ್ ಟೆಲಿಮೆಟ್ರಿ",
    gpsTelemetryDesc: "ಕೃಷಿಮಿತ್ರ ಪ್ರಾದೇಶಿಕ ಕೃಷಿ ತಜ್ಞರ ಅಂತರ ಮತ್ತು ಹವಾಮಾನ ದತ್ತಾಂಶವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹೊಂದಿಸುತ್ತದೆ.",
    namasteFriend: "ನಮಸ್ತೆ ರೈತ ಮಿತ್ರರೇ!",
    customDashboardSub: "ಬೆಳೆ ರೋಗಗಳನ್ನು ತಕ್ಷಣವೇ ಪತ್ತೆ ಮಾಡಿ, ಹವಾಮಾನ ಮುನ್ಸೂಚನೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ಕೃಷಿ ವಿಜ್ಞಾನಿಗಳನ್ನು ಸಂಪರ್ಕಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಬೀಜ ಅಂಗಡಿಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    weatherStrategy: "ಹವಾಮಾನ ಕಾರ್ಯತಂತ್ರ",
    metForecast: "ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    atmosphereModelsLoading: "ಹವಾಮಾನ ದತ್ತಾಂಶ ಮಾದರಿಗಳನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...",
    spraying: "ಸಿಂಪಡಣೆ",
    watering: "ನೀರಾವರಿ",
    full7DayPlan: "ಪೂರ್ಣ 7 ದಿನಗಳ ಯೋಜನೆ",
    pathology: "ಬೆಳೆ ರೋಗಶಾಸ್ತ್ರ",
    instantCropScan: "ತಕ್ಷಣದ ಬೆಳೆ ಸ್ಕ್ಯಾನ್",
    bentoScanDesc: "ಎಲೆಗಳು ಒಣಗುತ್ತಿವೆಯೇ? ಫೋಟೋ ತೆಗೆಯಿರಿ ಅಥವಾ ಸ್ಯಾಂಪಲ್ ಬೆಳೆ ಆರಿಸಿ. ಜೆಮಿನಿ ತಕ್ಷಣವೇ ರೋಗಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಿ ಉಪಯುಕ್ತ ಪರಿಹಾರಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    diagnosisSuite: "ರೋಗ ಪತ್ತೆ ವಿಭಾಗ",
    agriTrade: "ಕೃಷಿ ವ್ಯಾಪಾರ",
    registeredAgriShops: "ನೋಂದಾಯಿತ ಕೃಷಿ ಅಂಗಡಿಗಳು",
    nearby: "ಸಮೀಪದಲ್ಲಿದೆ",
    launchRoute: "ಮಾರ್ಗ ನಕ್ಷೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    agriScienceAdvisors: "ಕೃಷಿ ವಿಜ್ಞಾನ ಸಲಹೆಗಾರರು",
    certified: "ಪ್ರಮಾಣೀಕೃತ",
    bookedAppointments: "ಕಾಯ್ದಿರಿಸಿದ ಸಲಹಾ ಸಮಯ",
    approved: "ಅನುಮೋದಿಸಲಾಗಿದೆ",
    consultAdvisors: "ರಾಜ್ಯದ ಕೃಷಿ ತಜ್ಞರು ಅಥವಾ ಪ್ರಮಾಣೀಕೃತ ಕೃಷಿ ವೈದ್ಯರೊಂದಿಗೆ ಸಮಾಲೋಚಿಸಿ. ಮಣ್ಣಿನ ವರದಿಗಳಿಗಾಗಿ ನೇರ ಆಡಿಯೋ/ವಿಡಿಯೋ ಕರೆಗಳು ಅಥವಾ ಚಾಟ್‌ಗಳನ್ನು ಕಾಯ್ದಿರಿಸಿ.",
    consultExperts: "ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    previousDiagnostics: "ಹಿಂದಿನ ರೋಗ ಪತ್ತೆಗಳು",
    advice: "ಸಲಹೆ:",
    viewForecast: "ಮುನ್ಸೂಚನೆ ವೀಕ್ಷಿಸಿ",
    zone: "ವಲಯ",
    indianSemiArid: "ಸೆಮಿ-ಅರಿಡ್ ವಲಯ"
  },
  te: {
    tagline: "మీ వ్యవసాయ స్నేహితుడు",
    langSelector: "భాషను ఎంచుకోండి",
    cropScan: "పంట స్కాన్",
    voiceProblem: "వాయిస్ ప్రశ్న",
    weather: "వాతావరణం",
    experts: "వ్యవసాయ నిపుణులు",
    shops: "వ్యవసాయ షాపులు",
    scanHeading: "పంట సమస్యను స్కాన్ చేయండి",
    scanSub: "వ్యాధులు లేదా పోషకాల లోపాలను గుర్తించడానికి పంట ఫోటోను అప్‌లోడ్ చేయండి లేదా తీయండి",
    takePhoto: "ఫోటో తీయండి",
    uploadPhoto: "ఫోటో అప్‌లోడ్",
    sampleDiseases: "పరీక్ష కోసం నమూనా పంట వ్యాధులు",
    analyzing: "జెమిని ఏఐ విశ్లేషిస్తోంది...",
    results: "రోగ నిర్ధారణ నివేదిక",
    confidence: "విశ్వసనీయత స్థాయి",
    symptoms: "గమనించిన లక్షణాలు",
    treatment: "తక్షణ చికిత్సా ప్రణాళిక",
    prevention: "దీర్ఘకాలిక నివారణ సలహా",
    voiceTitle: "వ్యవసాయ సమస్యలను వాయిస్ ద్వారా తెలపండి",
    voiceSub: "మైక్ బటన్ నొక్కి మీ పంట సమస్యను చెప్పండి, సమాధానం వాయిస్ రూపంలో వినండి",
    recordStart: "రికార్డ్ చేయడానికి నొక్కండి",
    recording: "రికార్డింగ్ అవుతోంది... ఆపడానికి మళ్లీ నొక్కండి",
    converting: "జెమిని విశ్లేషించి సమాధానం ఇస్తోంది...",
    playSolution: "సమాధానం వినండి",
    orText: "లేదా మీ సమస్యను టైప్ చేయండి",
    askButton: "మిత్రను అడగండి",
    weatherTitle: "వాతావరణ వ్యవసాయ సలహాలు",
    weatherSub: "వారపు వాతావరణ సమాచారం తో పాటూ జెమిని పంట రక్షణ సూచనలు",
    current: "ప్రస్తుత వాతావరణం",
    weeklyForecast: "7-రోజుల వ్యవసాయ సూచన",
    gpsLocation: "జీపీఎస్ ఉపయోగించండి",
    searchCity: "నగరం లేదా ప్రాంతం",
    expertTitle: "వ్యవసాయ నిపుణుల పోర్టల్",
    expertSub: "కృషి విజ్ఞాన కేంద్రం (KVK) అధికారులు లేదా ప్రైవేట్ వ్యవసాయ శాస్త్రవేత్తలతో సంప్రదించండి",
    expertList: "సమీపంలోని వ్యవసాయ నిపుణులు",
    scheduleConsult: "అపాయింట్‌మెంట్ అడగండి",
    chatExpert: "నిపుణులతో చాట్ చేయండి",
    callExpert: "ఆడియో/వీడియో కాల్",
    bookingDate: "తేదీని ఎంచుకోండి",
    bookingTime: "అనుకూల సమయం",
    bookingNotes: "సమస్యను వివరించండి",
    bookButton: "ఉచిత కన్సల్టేషన్ బుక్ చేయండి",
    shopTitle: "సమీప వ్యవసాయ దుకాణాలు",
    shopSub: "మీకు దగ్గరలోని విత్తనాలు, ధృవీకరించబడిన ఎరువులు, క్రిమిసంహారకాలు మరియు నర్సరీలను కనుగొనండి",
    rating: "రేటింగ్",
    navigationRoute: "మార్గం మ్యాప్ చూపించు",
    contactNo: "షాపుకు కాల్ చేయండి",
    distanceLabel: "దూరం",
    helpPlaceholder: "ఉదా: నా టమోటా ఆకులు పసుపు రంగు అంచులతో గోధుమ రంగులోకి మారుతున్నాయి, ఏం చేయాలి?",
    farmerBoard: "రైతు బోర్డు",
    farmerToolbelt: "రైతు మెనూ",
    gpsTelemetry: "జీపీఎస్ టెలిమెట్రీ",
    gpsTelemetryDesc: "కృషిమిత్ర ప్రాంతీయ వ్యవసాయ నిపుణుల దూరం మరియు వాతావరణ సమాచారాన్ని స్వయంచాలకంగా సరిపోల్చుతుంది.",
    namasteFriend: "నమస్తే రైతు మిత్రమా!",
    customDashboardSub: "పంట తెగుళ్లను వెంటనే గుర్తించండి, వాతావరణ అలర్ట్‌లను పరిశీలించండి, కేవీకే శాస్త్రవేత్తలతో సంప్రదించండి మరియు మీ మాతృభాషలో విత్తనాల షాపులను అన్వేషించండి.",
    weatherStrategy: "వాతావరణ వ్యూహం",
    metForecast: "వాతావరణ సూచన",
    atmosphereModelsLoading: "వాతావరణ నమూనాలను డౌన్‌లోడ్ చేస్తోంది...",
    spraying: "ピచికారీ",
    watering: "నీటి పారుదల",
    full7DayPlan: "పూర్తి 7-రోజుల ప్రణాళిక",
    pathology: "పంట వ్యాధులు",
    instantCropScan: "తక్షణ పంట స్కాన్",
    bentoScanDesc: "ఆకులు ఎండిపోతున్నాయా? ఫోటో తీయండి లేదా నమూనా పంటను ఎంచుకోండి. జెమిని వెంటనే వ్యాధులను గుర్తించి చికిత్సా విధానాలను అందిస్తుంది.",
    diagnosisSuite: "వ్యాధి నిర్ధారణ విభాగం",
    agriTrade: "వ్యవసాయ వ్యాపారం",
    registeredAgriShops: "నమోదిత వ్యవసాయ దుకాణాలు",
    nearby: "దగ్గరలో ఉన్నాయి",
    launchRoute: "మార్గం మ్యాప్ ప్రారంభించండి",
    agriScienceAdvisors: "వ్యవసాయ శాస్త్ర సలహాదారులు",
    certified: "ధృవీకరించబడిన",
    bookedAppointments: "బుక్ చేసిన అపాయింట్‌మెంట్‌లు",
    approved: "ఆమోదించబడింది",
    consultAdvisors: "రాష్ట్ర వ్యవసాయ శాస్త్రవేత్తలు లేదా ధృవీకరించబడిన ఫార్మ్ డాక్టర్లతో సంప్రదించండి. నాణ్యమైన నేల నివేదికల కోసం నేరుగా ఆడియో/వీడియో కాల్స్ లేదా చాట్ బుక్ చేయండి.",
    consultExperts: "నిపుణులను సంప్రదించండి",
    previousDiagnostics: "మునుపటి రోగ నిర్ధారణలు",
    advice: "సలహా:",
    viewForecast: "వాతావరణ సూచన చూడండి",
    zone: "జోన్",
    indianSemiArid: "భారతీయ సెమీ-ఆరిడ్ జోన్"
  },
  ta: {
    tagline: "உங்கள் விவசாய நண்பன்",
    langSelector: "மொழியைத் தேர்வுசெய்",
    cropScan: "பயிர் ஸ்கேன்",
    voiceProblem: "குரல் வழி கேள்வி",
    weather: "வானிலை",
    experts: "விவசாய நிபுணர்கள்",
    shops: "விவசாய கடைகள்",
    scanHeading: "பயிர் பிரச்சனையை ஸ்கேன் செய்க",
    scanSub: "நோய்கள் அல்லது ஊட்டச்சத்து குறைபாடுகளை உடனடியாகக் கண்டறிய உங்கள் பயிரின் புகைப்படத்தைப் பதிவேற்றவும் அல்லது எடுக்கவும்",
    takePhoto: "புகைப்படம் எடு",
    uploadPhoto: "புகைப்படம் பதிவேற்று",
    sampleDiseases: "சோதனைக்கான மாதிரி பயிர் நோய்கள்",
    analyzing: "ஜெமினி AI பகுப்பாய்வு செய்கிறது...",
    results: "பயிர் நோய் அறிக்கை",
    confidence: "நம்பகத்தன்மை அளவு",
    symptoms: "கண்டறியப்பட்ட அறிகுறிகள்",
    treatment: "உடனடி சிகிச்சை முறை",
    prevention: "நீண்ட கால தடுப்பு ஆலோசனைகள்",
    voiceTitle: "விவசாய பிரச்சனைகளை குரல் மூலம் கூறவும்",
    voiceSub: "மைக் பொத்தானை அழுத்தி, உங்கள் விவசாயப் பிரச்சனையைத் தெரிவித்து, குரல் வடிவில் தீர்வைக் கேளுங்கள்",
    recordStart: "பதிவு செய்ய அழுத்தவும்",
    recording: "பதிவாகிறது... நிறுத்த மீண்டும் அழுத்தவும்",
    converting: "ஜெமினி மூலம் தீர்வு காணப்படுகிறது...",
    playSolution: "தீர்வை கேட்கவும்",
    orText: "அல்லது உங்கள் பிரச்சனையை எழுதவும்",
    askButton: "மித்ராவிடம் கேளுங்கள்",
    weatherTitle: "வானிலை விவசாய ஆலோசனைகள்",
    weatherSub: "வாராந்திர வானிலை விவரங்களுடன் ஜெமினி பயிர் பாதுகாப்பு வழிகாட்டுதல்கள்",
    current: "தற்போதைய வானிலை",
    weeklyForecast: "7-நாள் விவசாய வானிலை அறிக்கை",
    gpsLocation: "ஜிபிஎஸ் பயன்படுத்தவும்",
    searchCity: "நகரம் அல்லது மாவட்டத்தை உள்ளிடவும்",
    expertTitle: "விவசாய நிபுணர்கள் தளம்",
    expertSub: "அரசு कृषि विज्ञान केंद्र (KVK) அதிகாரிகள் அல்லது தனியார் விவசாய நிபுணர்களிடம் ஆலோசனை பெறுக",
    expertList: "அருகிலுள்ள விவசாய நிபுணர்கள்",
    scheduleConsult: "சந்திப்பை முன்பதிவு செய்க",
    chatExpert: "நிபுணருடன் அரட்டையடிக்க",
    callExpert: "ஆடியோ/வீடியோ அழைப்பு",
    bookingDate: "தேதியைத் தேர்ந்தெடுக்கவும்",
    bookingTime: "விருப்பமான நேரம்",
    bookingNotes: "பிரச்சனையை விவரிக்கவும்",
    bookButton: "இலவச ஆலோசனையை முன்பதிவு செய்க",
    shopTitle: "அருகிலுள்ள விவசாயக் கடைகள்",
    shopSub: "உங்களுக்கு அருகிலுள்ள விதை, சான்றளிக்கப்பட்ட உரங்கள், பூச்சிக்கொல்லி மற்றும் நர்சரிகளைக் கண்டறியவும்",
    rating: "மதிப்பீடு",
    navigationRoute: "வழி வரைபடத்தைக் காட்டு",
    contactNo: "கடைக்கு அழைக்கவும்",
    distanceLabel: "தொலைவு",
    helpPlaceholder: "உதாரணம்: எனது தக்காளி இலைகள் மஞ்சள் வளையங்களுடன் பழுப்பு நிறமாக மாறுகின்றன, நான் என்ன செய்ய வேண்டும்?",
    farmerBoard: "விவசாயி வாரியம்",
    farmerToolbelt: "விவசாயி மெனு",
    gpsTelemetry: "ஜிபிஎஸ் டெலிமெட்ரி",
    gpsTelemetryDesc: "கிருஷிமித்ரா பிராந்திய விவசாய நிபுணர்களின் தூரம் மற்றும் வானிலை தரவுகளை தானாகவே பொருத்துகிறது.",
    namasteFriend: "வணக்கம் விவசாய நண்பரே!",
    customDashboardSub: "பயிர் நோய்களை உடனடியாகக் கண்டறியவும், வானிலை எச்சரிக்கைகளைச் சரிபார்க்கவும், கேவிகே விஞ்ஞானிகளுடன் கலந்தாலோசிக்கவும் அல்லது உங்கள் தாய்மொழியில் விதை விவரங்களை அறியவும்.",
    weatherStrategy: "வானிலை உத்தி",
    metForecast: "வானிலை அறிக்கை",
    atmosphereModelsLoading: "வானிலை மாதிரிகளைப் பதிவிறக்குகிறது...",
    spraying: "தெளித்தல்",
    watering: "நீர் பாய்ச்சுதல்",
    full7DayPlan: "முழு 7 நாள் திட்டம்",
    pathology: "பயிர் நோயியல்",
    instantCropScan: "உடனடி பயிர் ஸ்கேன்",
    bentoScanDesc: "இலைகள் கருகுகிறதா? புகைப்படம் எடுக்கவும் அல்லது மாதிரி பயிரைத் தேர்ந்தெடுக்கவும். ஜெமினி உடனடியாக பூச்சிக் குறைபாடுகளைக் கண்டறிந்து தீர்வுகளைத் தரும்.",
    diagnosisSuite: "இலை நோய் தொகுதி",
    agriTrade: "விவசாய வர்த்தகம்",
    registeredAgriShops: "பதிவுசெய்யப்பட்ட விவசாயக் கடைகள்",
    nearby: "அருகில் உள்ளது",
    launchRoute: "வழி வரைபடத்தைக் காட்டு",
    agriScienceAdvisors: "விவசாய அறிவியல் ஆலோசகர்கள்",
    certified: "சான்றளிக்கப்பட்ட",
    bookedAppointments: "முன்பதிவு செய்யப்பட்ட சந்திப்புகள்",
    approved: "அங்கீகரிக்கப்பட்டது",
    consultAdvisors: "மாநில விவசாய வல்லுநர்கள் அல்லது சான்றளிக்கப்பட்ட விவசாய மருத்துவர்களுடன் கலந்தாலோசிக்கவும். உயர்தர மண் அறிக்கைகளுக்கு நேரடி அழைப்புகள் அல்லது அரட்டைகளை முன்பதிவு செய்யவும்.",
    consultExperts: "நிபுணர்களிடம் ஆலோசனை பெறுக",
    previousDiagnostics: "முந்தைய பயிர் நோய் கண்டறிதல்",
    advice: "ஆலோசனை:",
    viewForecast: "வானிலை அறிக்கை பார்க்க",
    zone: "மண்டலம்",
    indianSemiArid: "இந்திய அரை வறண்ட மண்டலம்"
  },
  mr: {
    tagline: "तुमचा शेती मित्र",
    langSelector: "भाषा निवडा",
    cropScan: "पीक स्कॅन",
    voiceProblem: "आवाज प्रश्न",
    weather: "हवामान",
    experts: "कृषी तज्ञ",
    shops: "कृषी दुकाने",
    scanHeading: "पीक समस्या स्कॅन करा",
    scanSub: "रोगांचे किंवा पोषक घटकांच्या कमतरतेचे त्वरित निदान करण्यासाठी पिकाचा फोटो अपलोड करा किंवा काढा",
    takePhoto: "फोटो काढा",
    uploadPhoto: "फोटो अपलोड करा",
    sampleDiseases: "चाचणीसाठी नमुना पीक रोग",
    analyzing: "जेमिनी एआय विश्लेषण करत आहे...",
    results: "निदान अहवाल",
    confidence: "विश्वास पातळी",
    symptoms: "दिसणारी लक्षणे",
    treatment: "तातडीची उपचार योजना",
    prevention: "दीर्घकालीन प्रतिबंधात्मक सल्ला",
    voiceTitle: "तुमची शेती समस्या बोला",
    voiceSub: "माईक बटण दाबा, स्थानिक भाषेत पीक समस्या सांगा आणि उत्तर आवाजात ऐका",
    recordStart: "रेकॉर्डिंगसाठी दाबा",
    recording: "रेकॉर्डिंग सुरू आहे... थांबवण्यासाठी पुन्हा दाबा",
    converting: "जेमिनी विश्लेषण करत आहे...",
    playSolution: "समाधान ऐका",
    orText: "किंवा तुमची समस्या लिहा",
    askButton: "मित्राला विचारा",
    weatherTitle: "हवामान आधारित कृषी सल्ला",
    weatherSub: "साप्ताहिक हवामान अंदाज आणि जेमिनी पीक संरक्षण सूचना",
    current: "सध्याचे हवामान",
    weeklyForecast: "७-दिवसांचा कृषी अंदाज",
    gpsLocation: "जीपीएस वापरा",
    searchCity: "शहर किंवा विभाग टाका",
    expertTitle: "कृषी तज्ञ पोर्टल",
    expertSub: "सरकारी कृषी विज्ञान केंद्र (KVK) अधिकारी किंवा खाजगी कृषी तज्ञांशी चर्चा करा",
    expertList: "नजीकचे उपलब्ध कृषी तज्ञ",
    scheduleConsult: "भेट निश्चित करा",
    chatExpert: "तज्ञांशी चॅट करा",
    callExpert: "ऑडिओ/व्हिडिओ कॉल",
    bookingDate: "तारीख निवडा",
    bookingTime: "वेळ निवडा",
    bookingNotes: "समस्या सांगा",
    bookButton: "मोफत भेट बुक करा",
    shopTitle: "नजीकची कृषी दुकाने",
    shopSub: "तुमच्या जवळचे बियाणे, प्रमाणित खते, कीटकनाशके आणि रोपवाटिका शोधा",
    rating: "रेटिंग",
    navigationRoute: "नक्षा दाखवा",
    contactNo: "दुकानदाराला कॉल करा",
    distanceLabel: "अंतर",
    helpPlaceholder: "उदा: माझ्या टोमॅटोची पाने पिवळ्या कडांसह तपकिरी होत आहेत, मी काय करू?",
    farmerBoard: "शेतकरी मंडळ",
    farmerToolbelt: "शेतकरी मेनू",
    gpsTelemetry: "जीपीएस टेलिमेट्री",
    gpsTelemetryDesc: "कृषिमित्र प्रादेशिक कृषी तज्ञांचे अंतर आणि हवामान डेटा स्वयंचलितपणे जुळवतो।",
    namasteFriend: "नमस्ते शेतकरी मित्रा!",
    customDashboardSub: "पीक रोगांचे त्वरित निदान करा, हवामान इशारे तपासा, कृषी वैज्ञानिकांशी चर्चा करा किंवा तुमच्या मातृभाषेत कृषी दुकाने शोधा।",
    weatherStrategy: "हवामान नियोजन",
    metForecast: "हवामान अंदाज",
    atmosphereModelsLoading: "हवामान मॉडेल डाउनलोड होत आहेत...",
    spraying: "फवारणी",
    watering: "सिंचन",
    full7DayPlan: "पूर्ण ७-दिवसीय नियोजन",
    pathology: "पीक रोगशास्त्र",
    instantCropScan: "त्वरित पीक स्कॅन",
    bentoScanDesc: "पाने खराब होत आहेत? फोटो काढा किंवा नमुना पीक निवडा। जेमिनी त्वरित कीड व रोगांची ओळख पटवून उपाय सुचवेल।",
    diagnosisSuite: "रोग निदान विभाग",
    agriTrade: "कृषी व्यापार",
    registeredAgriShops: "नोंदणीकृत कृषी दुकाने",
    nearby: "जवळपास",
    launchRoute: "मार्ग नकाशा उघडा",
    agriScienceAdvisors: "कृषी विज्ञान सल्लागार",
    certified: "प्रमाणित",
    bookedAppointments: "निश्चित केलेल्या भेटी",
    approved: "मंजूर",
    consultAdvisors: "शासकीय कृषी तज्ञ किंवा प्रमाणित डॉक्टरांशी सल्लामसलत करा। चांगल्या माती अहवालासाठी थेट कॉल किंवा चॅट बुक करा।",
    consultExperts: "तज्ञांशी चर्चा करा",
    previousDiagnostics: "पूर्वीचे रोग निदान",
    advice: "सल्ला:",
    viewForecast: "अंदाज पहा",
    zone: "विभाग",
    indianSemiArid: "भारतीय अर्ध-शुष्क प्रदेश"
  },
  bn: {
    tagline: "আপনার চাষের বন্ধু",
    langSelector: "ভাষা নির্বাচন করুন",
    cropScan: "ফসল স্ক্যান",
    voiceProblem: "ভয়েস সমস্যা",
    weather: "আবহাওয়া",
    experts: "কৃষি বিশেষজ্ঞ",
    shops: "কৃষি দোকান",
    scanHeading: "ফসলের সমস্যা স্ক্যান করুন",
    scanSub: "রোগ বা পুষ্টির অভাব সনাক্ত করতে আপনার ফসলের ছবি আপলোড বা ক্যামেরা ব্যবহার করে তুলুন",
    takePhoto: "ছবি তুলুন",
    uploadPhoto: "ছবি আপলোড করুন",
    sampleDiseases: "পরীক্ষার নমুনা ফসল ও রোগ তালিকা",
    analyzing: "জেমিনি এআই বিশ্লেষণ করছে...",
    results: "রোগ নির্ণয় প্রতিবেদন",
    confidence: "নির্ভরযোগ্যতার মাত্রা",
    symptoms: "পরিলক্ষিত লক্ষণসমূহ",
    treatment: "জরুরী চিকিৎসা পরিকল্পনা",
    prevention: "দীর্ঘমেয়াদী প্রতিরোধ পরামর্শ",
    voiceTitle: "আপনার কৃষি সমস্যা ভয়েসে বলুন",
    voiceSub: "মাইক্রোফোন টিপুন, আপনার নিজের ভাষায় ফসলের রোগ বা সমস্যার কথা বলুন এবং উত্তরটি ভয়েসে শুনুন",
    recordStart: "রেকর্ড করতে স্পর্শ করুন",
    recording: "রেকর্ড হচ্ছে... বন্ধ করতে আবার স্পর্শ করুন",
    converting: "জেমিনি সমাধান খুঁজছে...",
    playSolution: "সমাধান শুনুন",
    orText: "অথবা সমস্যা লিখে পাঠান",
    askButton: "মিত্রকে জিজ্ঞাসা করুন",
    weatherTitle: "আবহাওয়া ভিত্তিক কৃষি পরামর্শ",
    weatherSub: "সাপ্তাহিক আবহাওয়া সম্পর্কিত তথ্যের ওপর জেমিনি ফসল সুরক্ষা নির্দেশিকা",
    current: "বর্তমান আবহাওয়া",
    weeklyForecast: "৭-দিনের কৃষি পূর্বাভাস",
    gpsLocation: "জিপিএস অবস্থান ব্যবহার করুন",
    searchCity: "শহর বা অঞ্চল লিখুন",
    expertTitle: "কৃষি বিশেষজ্ঞ পোর্টাল",
    expertSub: "সরকারী কৃষি বিজ্ঞান কেন্দ্র (KVK) কর্মকর্তা বা সহযোগী কৃষি বিশেষজ্ঞদের পরামর্শ নেন",
    expertList: "নিকটবর্তী কৃষি বিশেষজ্ঞদের তালিকা",
    scheduleConsult: "সাক্ষাতের সময় নির্ধারণ করুন",
    chatExpert: "বিশেষজ্ঞদের সাথে চ্যাট করুন",
    callExpert: "অডিও/ভিডিও কল",
    bookingDate: "তারিখ নির্বাচন করুন",
    bookingTime: "পছন্দের সময়",
    bookingNotes: "আপনার সমস্যার সমস্যাটি বলুন",
    bookButton: "বিনামূল্যে স্লট বুক করুন",
    shopTitle: "নিকটবর্তী কৃষি দোকানসমূহ",
    shopSub: "নিকটবর্তী শংসাপত্র বীজ, সার, কীটনাশক এবং নার্সারি খুঁজুন",
    rating: "রেটিং",
    navigationRoute: "মানচিত্রে রুট দেখুন",
    contactNo: "দোকানে কল করুন",
    distanceLabel: "দূরত্ব",
    helpPlaceholder: "উদাঃ আমার টমেটো গাছের পাতাগুলি বর্ডার হলুদ রঙের সাথে বাদামী হয়ে যাচ্ছে, কি করা উচিত?",
    farmerBoard: "কৃষক বোর্ড",
    farmerToolbelt: "কৃষক মেনু",
    gpsTelemetry: "জিপিএস টেলিমেট্রি",
    gpsTelemetryDesc: "কৃষিমিথ্রা আঞ্চলিক কৃষি বিশেষজ্ঞদের দূরত্ব এবং আবহাওয়া সংক্রান্ত তথ্য স্বয়ংক্রিয়ভাবে সামঞ্জস্য করে।",
    namasteFriend: "নমস্কার কৃষক বন্ধু!",
    customDashboardSub: "ফসলের রোগ তৎক্ষণাৎ নির্ণয় করুন, আবহাওয়া আপডেট চেক করুন, কৃষি বিজ্ঞানীদের সাথে পরামর্শ করুন বা মাতৃভাষায় বীজের দোকান সন্ধান করুন।",
    weatherStrategy: "আবহাওয়া কৌশল",
    metForecast: "আবহাওয়া পূর্বাভাস",
    atmosphereModelsLoading: "আবহাওয়া মডেল ডাউনলোড হচ্ছে...",
    spraying: "স্প্রে করা",
    watering: "জল সেচ",
    full7DayPlan: "সাপ্তাহিক ৭ দিনের প্ল্যান",
    pathology: "রোগতত্ত্ব",
    instantCropScan: "তাত্ক্ষণিক ফসল স্ক্যান",
    bentoScanDesc: "পাতা নষ্ট হচ্ছে? ছবি তুলুন বা নমুনা ফসল নির্বাচন করুন। জেমিনি তৎক্ষণাৎ রোগ চিহ্নিত করে সমাধান দেবে।",
    diagnosisSuite: "রোগ নির্ণয় বিভাগ",
    agriTrade: "কৃষি বাণিজ্য",
    registeredAgriShops: "নিবন্ধিত কৃষি দোকান",
    nearby: "কাছাকাছি",
    launchRoute: "মানচিত্রে রুট দেখুন",
    agriScienceAdvisors: "কৃষি বিজ্ঞান উপদেষ্টা",
    certified: "শংসাপত্রপ্রাপ্ত",
    bookedAppointments: "বुक করা অ্যাপয়েন্টমেন্ট",
    approved: "অনুমোদিত",
    consultAdvisors: "রাজ্যের কৃষি বিশেষজ্ঞ বা শংসাপত্রপ্রাপ্ত খামার ডাক্তারদের পরামর্শ নেন। মাটির গুণগত রিপোর্টের জন্য সরাসরি অডিও/ভিডিও বা চ্যাট বুক করুন।",
    consultExperts: "বিশেষজ্ঞদের পরামর্শ নেন",
    previousDiagnostics: "পূর্ববর্তী রোগ নির্ণয়ের ইতিহাস",
    advice: "পরামর্শ:",
    viewForecast: "পূর্বাভাস দেখুন",
    zone: "অঞ্চল",
    indianSemiArid: "भारतीय अर्ध-शुष्क क्षेत्र"
  },
  ml: {
    tagline: "നിങ്ങളുടെ കർഷക സുഹൃത്ത്",
    langSelector: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    cropScan: "വിള സ്കാൻ",
    voiceProblem: "ശബ്ദത്തിലൂടെ ചോദിക്കാം",
    weather: "കാലാവസ്ഥ",
    experts: "കൃഷി വിദഗ്ദ്ധർ",
    shops: "കൃഷി കടകൾ",
    scanHeading: "വിള പ്രശ്നം സ്കാൻ ചെയ്യുക",
    scanSub: "രോഗങ്ങളോ പോഷകക്കുറവോ കണ്ടെത്തുന്നതിന് വിളയുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുകയോ ക്യാമറ ഉപയോഗിച്ച് എടുക്കുകയോ ചെയ്യുക",
    takePhoto: "ഫോട്ടോ എടുക്കുക",
    uploadPhoto: "ഫോട്ടോ അപ്‌ലോഡ്",
    sampleDiseases: "പരീക്ഷണത്തിനുള്ള സാമ്പിൾ വിള രോഗങ്ങൾ",
    analyzing: "ജെമിനി എഐ വിശകലനം ചെയ്യുന്നു...",
    results: "രോഗനിർണ്ണയ റിപ്പോർട്ട്",
    confidence: "വിശ്വാസ്യത നില",
    symptoms: "കണ്ടെത്തിയ രോഗലക്ഷണങ്ങൾ",
    treatment: "ഉടൻ ചെയ്യേണ്ട പ്രതിവിധികൾ",
    prevention: "ഭാവിയിൽ തടയാനുള്ള നിർദ്ദേശങ്ങൾ",
    voiceTitle: "കൃഷി പ്രശ്നങ്ങൾ ശബ്ദത്തിലൂടെ ഉണർത്താം",
    voiceSub: "മൈക്ക് ബട്ടൺ അമർത്തി നിങ്ങളുടെ ഭാഷയിൽ വിള പ്രശ്നം പറയുക, ഉത്തരം വോയിസ് രൂപത്തിൽ കേൾക്കാം",
    recordStart: "റെക്കോർഡ് ചെയ്യാൻ അമർത്തുക",
    recording: "റെക്കോർഡിംഗ് നടക്കുന്നു... നിർത്താൻ വീണ്ടും അമർത്തുക",
    converting: "ജെമിനി ഉത്തരം തയ്യാറാക്കുന്നു...",
    playSolution: "ഉത്തരം കേൾക്കാം",
    orText: "അല്ലെങ്കിൽ നിങ്ങളുടെ പ്രശ്നം എഴുതുക",
    askButton: "മിത്രയോടെ ചോദിക്കാം",
    weatherTitle: "കാലാവസ്ഥാ കൃഷി നിർദ്ദേശങ്ങൾ",
    weatherSub: "വാര്ഷിക കാലാവസ്ഥാ പ്രവചനവും അതിനനുസരിച്ചുള്ള ജെമിനി കൃഷി ഉപദേശങ്ങളും",
    current: "തത്സമയ കാലാവസ്ഥ",
    weeklyForecast: "7-ദിന കൃഷി പ്രവചനം",
    gpsLocation: "ജിപിഎസ് ഉപയോഗിക്കുക",
    searchCity: "നഗരമോ താലൂക്കോ നൽകുക",
    expertTitle: "കൃഷി ശാസ്ത്രജ്ഞരുടെ പോർട്ടൽ",
    expertSub: "സർക്കാർ കൃഷി വിജ്ഞാൻ കേന്ദ്ര (KVK) ഉദ്യോഗസ്ഥരുമായോ കൃഷി വിദഗ്ദ്ധരുമായോ ബന്ധപ്പെടുക",
    expertList: "ലഭ്യമായ കൃഷി വിദഗ്ദ്ധർ",
    scheduleConsult: "കൂടിക്കാഴ്ച നിശ്ചയിക്കുക",
    chatExpert: "വിദഗ്ദ്ധനുമായി ചാറ്റ് ചെയ്യാം",
    callExpert: "ഓഡിയോ/വീഡിയോ കോൾ",
    bookingDate: "തീയതി തിരഞ്ഞെടുക്കുക",
    bookingTime: "അനുയോജ്യമായ സമയം",
    bookingNotes: "പ്രശ്നത്തെക്കുറിച്ച് വിവരണം നൽകുക",
    bookButton: "സൗജന്യ അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക",
    shopTitle: "സമീപത്തെ കൃഷി കടകൾ",
    shopSub: "നിങ്ങൾക്ക് ചുറ്റുമുള്ള വിത്ത്, സാക്ഷ്യപ്പെടുത്തിയ വളങ്ങൾ, കീടനാശിനി കടകൾ, നഴ്സറികൾ എന്നിവ കണ്ടെത്തുക",
    rating: "റേറ്റിംഗ്",
    navigationRoute: "വഴി മാപ്പ് കാണിക്കുക",
    contactNo: "കടയിലേക്ക് വിളിക്കുക",
    distanceLabel: "ദൂരം",
    helpPlaceholder: "ഉദാഹരണം: തക്കാളിയിലകൾ മഞ്ഞ അരികുകളോടെ കരിഞ്ഞു പോകുന്നു, പരിഹാരം എന്താണ്?",
    farmerBoard: "കർഷക ബോർഡ്",
    farmerToolbelt: "കർഷക മെനു",
    gpsTelemetry: "ജിപിഎസ് ടെലിമെട്രി",
    gpsTelemetryDesc: "കൃഷിമിത്ര പ്രാദേശിക കൃഷി വിദഗ്ദ്ധരുടെ ദൂരവും കാലാവസ്ഥാ വിവരങ്ങളും സ്വയമേവ ക്രമീകരിക്കുന്നു.",
    namasteFriend: "നമസ്തേ കർഷക സുഹൃത്തേ!",
    customDashboardSub: "വിള രോഗങ്ങൾ ഉടൻ കണ്ടെത്തുക, കാലാവസ്ഥാ അറിയിപ്പുകൾ പരിശോധിക്കുക, കൃഷി ശാസ്ത്രജ്ഞരുമായി ബന്ധപ്പെടുക അല്ലെങ്കിൽ നിങ്ങളുടെ മാതൃഭാഷയിൽ കടകൾ കണ്ടെത്തുക.",
    weatherStrategy: "കാലാവസ്ഥാ ആസൂത്രണം",
    metForecast: "കാലാവസ്ഥാ പ്രവചനം",
    atmosphereModelsLoading: "കാലാവസ്ഥാ മോഡലുകൾ വിവരങ്ങൾ ലഭ്യമാക്കുന്നു...",
    spraying: "തളിക്കൽ",
    watering: "നനയ്ക്കൽ",
    full7DayPlan: "7 ദിവസത്തെ പൂർണ്ണ പദ്ധതി",
    pathology: "രോഗശാസ്ത്രം",
    instantCropScan: "ഉടൻ വിള സ്കാൻ",
    bentoScanDesc: "ഇലകൾ കരിയുന്നുണ്ടോ? ഫോട്ടോ എടുക്കുക അല്ലെങ്കിൽ സാമ്പിൾ തിരഞ്ഞെടുക്കുക. ജെമിനി ഉടൻ കീടബാധകൾ കണ്ടെത്തി പ്രതിവിധി നിർദ്ദേശിക്കും.",
    diagnosisSuite: "രോഗനിർണ്ണയ വിഭാഗം",
    agriTrade: "കാർഷിക വ്യാപാരം",
    registeredAgriShops: "രജിസ്റ്റർ ചെയ്ത കൃഷി കടകൾ",
    nearby: "സമീപത്ത്",
    launchRoute: "വഴി മാപ്പ് കാണിക്കുക",
    agriScienceAdvisors: "കാർഷിക ശാസ്ത്ര ഉപദേശകർ",
    certified: "സാക്ഷ്യപ്പെടുത്തിയത്",
    bookedAppointments: "ബുക്ക് ചെയ്ത കൂടിക്കാഴ്ചകൾ",
    approved: "അംഗീകരിച്ചു",
    consultAdvisors: "കൃഷി വിദഗ്ദ്ധരുമായോ സാക്ഷ്യപ്പെടുത്തിയ ഡോക്ടർമാരുമായോ കൂടിക്കാഴ്ച നടത്തുക. മികച്ച കൺസൾട്ടേഷനായി ഓഡിയോ/വീഡിയോ കോളുകൾ അല്ലെങ്കിൽ ചാറ്റ് ബുക്ക് ചെയ്യാം.",
    consultExperts: "വിദഗ്ദ്ധരെ കാണുക",
    previousDiagnostics: "മുൻകാല രോഗനിർണ്ണയങ്ങൾ",
    advice: "നിർദ്ദേശം:",
    viewForecast: "പ്രവചനം കാണുക",
    zone: "മേഖല",
    indianSemiArid: "ഇന്ത്യൻ അർദ്ധ-വരണ്ട മേഖല"
  },
  gu: {
    tagline: "તમારો ખેતી મિત્ર",
    langSelector: "ભાષા પસંદ કરો",
    cropScan: "પાક સ્કેન",
    voiceProblem: "અવાજ પ્રશ્ન",
    weather: "હવામાન",
    experts: "કૃષિ નિષ્ણાતો",
    shops: "કૃષિ દુકાનો",
    scanHeading: "પાક રોગ સ્કેન કરો",
    scanSub: "પાકના રોગો અથવા પોષક તત્વોની ઉણપને ત્વરિત ઓળખવા પાકનો ફોટો અપલોડ કે કેમેરાથી કેપ્ચર કરો",
    takePhoto: "ફોટો લો",
    uploadPhoto: "ફોટો અપલોડ કરો",
    sampleDiseases: "પરીક્ષણ માટે નમૂના પાક રોગો",
    analyzing: "જેમિની એઆઈ વિશ્લેષણ કરે છે...",
    results: "રોગ નિદાન રીપોર્ટ",
    confidence: "વિશ્વાસ સ્તર",
    symptoms: "જોવા મળેલા લક્ષણો",
    treatment: "તાત્કાલિક સારવારના પગલાં",
    prevention: "લાંબા ગાળાના બચાવ પગલાં",
    voiceTitle: "ખેતી સમસ્યાઓ બોલીને જણાવો",
    voiceSub: "માઈક બટન દબાવો, ખેતી સમસ્યા તમારી પ્રાદેશિક ભાષામાં જણાવો અને ઉત્તર ઓડિયોમાં સાંભળો",
    recordStart: "રેકોર્ડિંગ કરવા ક્લિક કરો",
    recording: "રેકોર્ડિંગ શરૂ છે... રોકવા ફરી ક્લિક કરો",
    converting: "જેમિની ઉકેલ શોધી રહ્યું છે...",
    playSolution: "ઉકેલ ઓડિયોમાં સાંભળો",
    orText: "અથવા પ્રશ્ન લખીને મોકલો",
    askButton: "મિત્રને પૂછો",
    weatherTitle: "હવામાન કૃષિ સલાહ",
    weatherSub: "સાપ્તાહિક નીતિઓની માહિતી સાથે જેમીની આધારિત વાવણી સલાહ",
    current: "વર્તમાન હવામાન",
    weeklyForecast: "૭-દિવસીય કૃષિ પૂર્વાનુમાન",
    gpsLocation: "જીપીએસ વાપરો",
    searchCity: "શહેર અથવા જિલ્લો દાખલ કરો",
    expertTitle: "કૃષિ સલાહકાર કેન્દ્ર",
    expertSub: "સરકારી કૃષિ વિજ્ઞાન કેન્દ્ર (KVK) અધિકારીઓ અથવા ખાનગી કૃષિ વૈજ્ઞાનિકોનો સંપર્ક કરો",
    expertList: "નજીકના ઉપલબ્ધ કૃષિ તજજ્ઞો",
    scheduleConsult: "મુલાકાતનો સમય મળો",
    chatExpert: "નિષ્ણાત સાથે વાતચીત કરો",
    callExpert: "ઓડિયો/વીડિયો કોલ",
    bookingDate: "તારીખ પસંદ કરો",
    bookingTime: "પસંદગીનો સમય",
    bookingNotes: "સમસ્યાની વિગત આપો",
    bookButton: "નિઃશુલ્ક મુલાકાત બુક કરો",
    shopTitle: "નજીકની કૃષિ દુકાનો",
    shopSub: "પ્રમાણિત બિયારણ, ખાતર, જંતુનાશક દવાઓ અને નર્સરીની માહિતી મેળવો",
    rating: "રેટિંગ",
    navigationRoute: "નકશો બતાવો",
    contactNo: "દુકાનદારને કોલ કરો",
    distanceLabel: "અંતર",
    helpPlaceholder: "દા.ત. મારા ટામેટાના પાંદડા પીળી બોર્ડર સાથે કથ્થઈ પડી રહ્યા છે, મારે શું કરવું?",
    farmerBoard: "ખેડૂત બોર્ડ",
    farmerToolbelt: "ખેડૂત મેનુ",
    gpsTelemetry: "જીપીએસ ટેલિમેટ્રી",
    gpsTelemetryDesc: "કૃષિમિત્ર પ્રાદેશિક કૃષિ નિષ્ણાતોનું અંતર અને હવામાન ડેટા આપમેળે મેળવે છે.",
    namasteFriend: "નમસ્તે ખેડૂત મિત્ર!",
    customDashboardSub: "પાકના રોગોનું ત્વરિત નિદાન કરો, હવામાનની ચેતવણીઓ તપાસો, કૃષિ વૈજ્ઞાનિકોની સલાહ લો અથવા તમારી માતૃભાષામાં દુકાનો વિશે માહિતી મેળવો.",
    weatherStrategy: "હવામાન વ્યૂહરચના",
    metForecast: "હવામાન આગાહી",
    atmosphereModelsLoading: "હવામાન મોડેલ ડાઉનલોડ થઈ રહ્યું છે...",
    spraying: "છંટકાવ",
    watering: "સિંચાઈ / પાણી પાવું",
    full7DayPlan: "૭-દિવસીય પૂર્ણ આયોજન",
    pathology: "રોગશાસ્ત્ર",
    instantCropScan: "ત્વરિત પાક સ્કેન",
    bentoScanDesc: "પાંદડા બગડી રહ્યા છે? ફોટો લો અથવા નમૂનો પસંદ કરો. જેમિની તરત જ રોગ ઓળખીને સારવારની યાદી આપશે.",
    diagnosisSuite: "રોગ નિદાન વિભાગ",
    agriTrade: "કૃષિ વ્યાપાર",
    registeredAgriShops: "નોંધાયેલ કૃષિ દુકાનો",
    nearby: "નજીકમાં",
    launchRoute: "નકશો બતાવો",
    agriScienceAdvisors: "કૃષિ વિજ્ઞાન સલાહકારો",
    certified: "પ્રમાણિત",
    bookedAppointments: "બુક કરેલ મુલાકાતો",
    approved: "મંજૂર",
    consultAdvisors: "રાજ્યના કૃષિ નિષ્ણાતો અથવા પ્રમાણિત ડોક્ટર્સનો સંપર્ક કરો. ઉચ્ચ ગુણવત્તાવાળા સોઇલ રિપોર્ટ્સ માટે સીધા જ કોલ અથવા ચેટ બુક કરો.",
    consultExperts: "નિષ્ણાતોની સલાહ લો",
    previousDiagnostics: "અગાઉના પાક રોગ નિદાન",
    advice: "સલાહ:",
    viewForecast: "હવામાન આગાહી જુઓ",
    zone: "ઝોન",
    indianSemiArid: "અર્ધ-શુષ્ક ભારતીય ક્ષેત્ર"
  },
  pa: {
    tagline: "ਤੁਹਾਡਾ ਖੇਤੀ ਮਿੱਤਰ",
    langSelector: "ਭਾਸ਼ਾ ਚੁਣੋ",
    cropScan: "ਫ਼ਸਲ ਸਕੈਨ",
    voiceProblem: "ਆਵਾਜ਼ ਰਾਹੀਂ ਪੁੱਛੋ",
    weather: "ਮੌਸਮ",
    experts: "ਖੇਤੀ ਮਾਹਰ",
    shops: "ਖੇਤੀ ਦੁਕਾਨਾਂ",
    scanHeading: "ਫ਼ਸਲ ਦੀ ਸਮੱਸਿਆ ਸਕੈਨ ਕਰੋ",
    scanSub: "ਬੀਮਾਰੀਆਂ ਜਾਂ ਪੋਸ਼ਕ ਤੱਤਾਂ ਦੀ ਕਮੀ ਦੀ ਤੁਰੰਤ ਪਛਾਣ ਕਰਨ ਲਈ ਫ਼ਸਲ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ ਜਾਂ ਖਿੱਚੋ",
    takePhoto: "ਫੋਟੋ ਖਿੱਚੋ",
    uploadPhoto: "ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    sampleDiseases: "ਟੈਸਟਿੰਗ ਲਈ ਨਮੂਨਾ ਫ਼ਸਲ ਬੀਮਾਰੀਆਂ",
    analyzing: "ਜੈਮਿਨੀ ਏਆਈ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...",
    results: "ਨਿਦਾਨ ਰਿਪੋਰਟ",
    confidence: "ਭਰੋਸਾ ਪੱਧਰ",
    symptoms: "ਵੇਖੇ ਗਏ ਲੱਛਣ",
    treatment: "ਤੁਰੰਤ ਇਲਾਜ ਯੋਜਨਾ",
    prevention: "ਦੀਰਘਕਾਲੀ ਰੋਕਥਾਮ ਸਲਾਹ",
    voiceTitle: "ਖੇਤੀ ਸਮੱਸਿਆਵਾਂ ਬੋਲ ਕੇ ਦੱਸੋ",
    voiceSub: "ਮਾਈਕ ਬਟਨ ਦਬਾਓ, ਆਪਣੀ ਖੇਤਰੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਮੱਸਿਆ ਬੋਲੋ ਅਤੇ ਸਮਾਧਾਨ ਆਵਾਜ਼ ਰਾਹੀਂ ਸੁਣੋ",
    recordStart: "ਰਿਕਾਰਡ ਕਰਨ ਲਈ ਦਬਾਓ",
    recording: "ਰਿਕਾਰਡਿੰਗ ਹੋ ਰਹੀ ਹੈ... ਰੋਕਣ ਲਈ ਫਿਰ ਦਬਾਓ",
    converting: "ਜੈਮਿਨੀ ਹੱਲ ਲੱਭ ਰਿਹਾ ਹੈ...",
    playSolution: "ਸਮਾਧਾਨ ਸੁਣੋ",
    orText: "ਜਾਂ ਆਪਣੀ ਸਮੱਸਿਆ ਲਿਖੋ",
    askButton: "ਮਿੱਤਰ ਨੂੰ ਪੁੱਛੋ",
    weatherTitle: "ਮੌਸਮ ਆਧਾਰਿਤ ਖੇਤੀ ਸਲਾਹ",
    weatherSub: "ਹਫ਼ਤਾਵਾਰੀ ਮੌਸਮ ਅਪਡੇਟ ਅਤੇ ਜੈਮਿਨੀ ਫ਼ਸਲ ਸੁਰੱਖਿਆ ਨਿਰਦੇਸ਼",
    current: "ਮੌਜੂਦਾ ਮੌਸਮ",
    weeklyForecast: "7-ਦਿਨ ਖੇਤੀ ਪੂਰਵ-ਅਨੁਮਾਨ",
    gpsLocation: "ਜੀਪੀਐਸ ਵਰਤੋਂ",
    searchCity: "ਸ਼ਹਿਰ ਜਾਂ ਖੇਤਰ ਭਰੋ",
    expertTitle: "ਖੇਤੀਬਾੜੀ ਮਾਹਰ ਪੋਰਟਲ",
    expertSub: "ਸਰਕਾਰੀ ਕ੍ਰਿਸ਼ੀ ਵਿਗਿਆਨ ਕੇਂਦਰ (KVK) ਅਫਸਰਾਂ ਜਾਂ ਨਿੱਜੀ ਖੇਤੀ ਵਿਗਿਆਨੀਆਂ ਨਾਲ ਸਲਾਹ ਕਰੋ",
    expertList: "ਨੇੜਲੇ ਉਪਲਬਧ ਖੇਤੀ ਮਾਹਰ",
    scheduleConsult: "ਮੁਲਾਕਾਤ ਤੈਅ ਕਰੋ",
    chatExpert: "ਮਾਹਰ ਨਾਲ ਚੈਟ ਕਰੋ",
    callExpert: "ਆਡੀਓ/ਵੀਡੀਓ ਕਾਲ",
    bookingDate: "ਤਾਰੀਖ ਚੁਣੋ",
    bookingTime: "ਸਮਾਂ ਚੋਣ",
    bookingNotes: "ਸਮੱਸਿਆ ਦਾ ਵੇਰਵਾ ਦਿਓ",
    bookButton: "ਮੁਫ਼ਤ ਸਲਾਹ ਬੁੱਕ ਕਰੋ",
    shopTitle: "ਨੇੜਲੀਆਂ ਖੇਤੀ ਦੁਕਾਨਾਂ",
    shopSub: "ਆਪਣੇ ਨੇੜੇ ਬੀਜ, ਪ੍ਰਮਾਣਿਤ ਖਾਦ, ਕੀਟਨਾਸ਼ਕ ਅਤੇ ਨਰਸਰੀਆਂ ਲੱਭੋ",
    rating: "ਰੇਟਿੰਗ",
    navigationRoute: "ਰੂਟ ਮੈਪ ਵੇਖੋ",
    contactNo: "ਦੁਕਾਨ ਨੂੰ ਕਾਲ ਕਰੋ",
    distanceLabel: "ਦੂਰੀ",
    helpPlaceholder: "ਉਦਾਹਰਨ: ਮੇਰੇ ਟਮਾਟਰ ਦੇ ਪੱਤੇ ਪੀਲੇ ਘੇਰਿਆਂ ਨਾਲ ਭੂਰੇ ਹੋ ਰਹੇ ਹਨ, ਕੀ ਕਰਾਂ?",
    farmerBoard: "ਕਿਸਾਨ ਬੋਰਡ",
    farmerToolbelt: "ਕਿਸਾਨ ਮੀਨੂ",
    gpsTelemetry: "ਜੀਪੀਐਸ ਟੈਲੀਮੈਟਰੀ",
    gpsTelemetryDesc: "ਕ੍ਰਿਸ਼ੀਮਿੱਤਰ ਖੇਤਰੀ ਖੇਤੀਬਾੜੀ ਮਾਹਰਾਂ ਦੀ ਦੂਰੀ ਅਤੇ ਮੌਸਮ ਸੰਬੰਧੀ ਡੇਟਾ ਨੂੰ ਆਪਣੇ ਆਪ ਮਿਲਾਉਂਦਾ ਹੈ।",
    namasteFriend: "ਨਮਸਤੇ ਕਿਸਾਨ ਵੀਰੋ!",
    customDashboardSub: "ਫ਼ਸਲੀ ਰੋਗਾਂ ਦਾ ਤੁਰੰਤ ਪਤਾ ਲਗਾਓ, ਮੌਸਮ ਦੇ ਅਲਰਟ ਦੇਖੋ, ਖੇਤੀ ਮਾਹਰਾਂ ਨਾਲ ਸਲਾਹ ਕਰੋ, ਜਾਂ ਆਪਣੀ ਮਾਂ-ਬੋਲੀ ਵਿੱਚ ਬੀਜਾਂ ਦੀਆਂ ਦੁਕਾਨਾਂ ਲੱਭੋ।",
    weatherStrategy: "ਮੌਸਮ ਰਣਨੀਤੀ",
    metForecast: "ਮੌਸਮ ਭਵਿੱਖਬਾਣੀ",
    atmosphereModelsLoading: "ਮੌਸਮ ਦੇ ਮਾਡਲ ਡਾਊਨਲੋਡ ਕੀਤੇ ਜਾ ਰਹੇ ਹਨ...",
    spraying: "ਸਪ੍ਰੇ ਕਰਨਾ",
    watering: "ਸਿੰਚਾਈ / ਪਾਣੀ ਦੇਣਾ",
    full7DayPlan: "7-ਦਿਨਾਂ ਦੀ ਪੂਰੀ ਯੋਜਨਾ",
    pathology: "ਰੋਗ ਵਿਗਿਆਨ",
    instantCropScan: "ਤੁਰੰਤ ਫ਼ਸਲ ਸਕੈਨ",
    bentoScanDesc: "ਪੱਤੇ ਖ਼ਰਾਬ ਹੋ ਰਹੇ ਹਨ? ਫੋਟੋ ਖਿੱਚੋ ਜਾਂ ਨਮੂਨਾ ਫ਼ਸਲ ਚੁਣੋ। ਜੈਮਿਨੀ ਤੁਰੰਤ ਕੀੜਿਆਂ ਦੀ ਪਛਾਣ ਕਰਕੇ ਇਲਾਜ ਦੀ ਸੂਚੀ ਦੇਵੇਗਾ।",
    diagnosisSuite: "ਨਿਦਾਨ ਵਿਭਾਗ",
    agriTrade: "ਖੇਤੀ ਵਪਾਰ",
    registeredAgriShops: "ਰਜਿਸਟਰਡ ਖੇਤੀ ਦੁਕਾਨਾਂ",
    nearby: "ਨੇੜੇ",
    launchRoute: "ਰੂਟ ਮੈਪ ਦੇਖੋ",
    agriScienceAdvisors: "ਖੇਤੀ ਵਿਗਿਆਨ ਸਲਾਹਕਾਰ",
    certified: "ਪ੍ਰਮਾਣਿਤ",
    bookedAppointments: "ਬੁੱਕ ਕੀਤੀਆਂ ਮੁਲਾਕਾਤਾਂ",
    approved: "ਮਨਜ਼ੂਰ",
    consultAdvisors: "ਸੂਬੇ ਦੇ ਖੇਤੀ ਵਿਗਿਆਨੀਆਂ ਜਾਂ ਪ੍ਰਮਾਣਿਤ ਖੇਤੀ ਡਾਕਟਰਾਂ ਨਾਲ ਸਲਾਹ ਕਰੋ। ਉੱਚ-ਗੁਣਵੱਤਾ ਵਾਲੀ ਮਿੱਟੀ ਦੀ ਰਿਪੋਰਟ ਲਈ ਸਿੱਧੇ ਕਾਲ ਜਾਂ ਚੈਟ ਬੁੱਕ ਕਰੋ।",
    consultExperts: "ਮਾਹਰਾਂ ਨਾਲ ਸਲਾਹ ਕਰੋ",
    previousDiagnostics: "ਪਿਛਲਾ ਨਿਦਾਨ ਇਤਿਹਾਸ",
    advice: "ਸਲਾਹ:",
    viewForecast: "ਭਵਿੱਖਬਾਣੀ ਦੇਖੋ",
    zone: "ਜ਼ੋਨ",
    indianSemiArid: "ਅਰਧ-ਖੁਸ਼ਕ ਭਾਰਤੀ ਖੇਤਰ"
  }
};
