/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LanguageConfig, SupportedLanguage } from "./types";

export const LANGUAGES: LanguageConfig[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    tagline: "Your Farming Friend",
    langSelector: "Choose Language",
    cropScan: "Crop Scan",
    voiceProblem: "Voice Query",
    weather: "Weather",
    experts: "Ag Experts",
    shops: "Agri Shops",
    scanHeading: "Scan Crop Problem",
    scanSub: "Upload or take a photo of your crop to instantly diagnose diseases or nutrient deficiencies",
    takePhoto: "Take Photo",
    uploadPhoto: "Upload Photo",
    sampleDiseases: "Test with Sample Crop Diseases",
    analyzing: "Analyzing with Gemini AI...",
    results: "Diagnostic Report",
    confidence: "Confidence Level",
    symptoms: "Symptoms Observed",
    treatment: "Immediate Treatment Plan",
    prevention: "Long-term Prevention Advice",
    voiceTitle: "Speak Your Farming Problem",
    voiceSub: "Hold the microphone, state your crop issue in your local language, and hear the solution read aloud",
    recordStart: "Tap to record & speak",
    recording: "Recording... Tap again to solve",
    converting: "Transcribing and solving with Gemini...",
    playSolution: "Listen to Solution",
    orText: "Or type your problem",
    askButton: "Ask Mitra",
    weatherTitle: "Weather Agricultural suggestions",
    weatherSub: "Weekly localized meteorological data paired with Gemini farming instructions",
    current: "Current Conditions",
    weeklyForecast: "7-Day Agri-Forecast",
    gpsLocation: "Use GPS Location",
    searchCity: "Enter City or Region",
    expertTitle: "Agriculture Experts Portal",
    expertSub: "Consult with government Krishi Vigyan Kendra officers or private agronomists",
    expertList: "Available Agronomists Nearby",
    scheduleConsult: "Schedule Appointment",
    chatExpert: "Chat with Expert",
    callExpert: "Audio/Video Call",
    bookingDate: "Select Date",
    bookingTime: "Preferred Time Slot",
    bookingNotes: "Describe your issue",
    bookButton: "Book Free Consultation",
    shopTitle: "Nearby Agri Shops & Seeds",
    shopSub: "Find seeds, certified fertilizers, crop protection shops, and nurseries near you",
    rating: "Rating",
    navigationRoute: "Show Route Map",
    contactNo: "Call Shop",
    distanceLabel: "Distance",
    helpPlaceholder: "Ex: My tomato leaves are turning brown with yellow halos, what should I do?"
  },
  hi: {
    tagline: "आपका खेती साथी",
    langSelector: "भाषा चुनें",
    cropScan: "फसल स्कैन",
    voiceProblem: "आवाज से पूछें",
    weather: "मौसम",
    experts: "कृषि विशेषज्ञ",
    shops: "कृषि दुकानें",
    scanHeading: "फसल समस्या स्कैन करें",
    scanSub: "बीमारियों या पोषक तत्वों की कमी का तुरंत निदान करने के लिए फसल की फोटो अपलोड करें या खींचें",
    takePhoto: "फ़ोटो खींचें",
    uploadPhoto: "फ़ोटो अपलोड करें",
    sampleDiseases: "परीक्षण के लिए नमूना फसल रोग",
    analyzing: "जेमिनी एआई विश्लेषण कर रहा है...",
    results: "निदान रिपोर्ट",
    confidence: "विश्वास स्तर",
    symptoms: "दिखने वाले लक्षण",
    treatment: "तत्काल उपचार योजना",
    prevention: "दीर्घकालिक रोकथाम सलाह",
    voiceTitle: "अपनी खेती की समस्या बोलें",
    voiceSub: "माइक बटन दबाएं, स्थानीय भाषा में फसल समस्या बताएं, और समाधान बोलकर सुनाया जाएगा",
    recordStart: "रिकॉर्ड करने के लिए दबाएं",
    recording: "रिकॉर्डिंग चालू है... रोकने के लिए पुनः दबाएं",
    converting: "जेमिनी द्वारा अनुवाद और समाधान किया जा रहा है...",
    playSolution: "समाधान सुनें",
    orText: "या अपनी समस्या लिखें",
    askButton: "मित्र से पूछें",
    weatherTitle: "मौसम आधारित कृषि सलाह",
    weatherSub: "साप्ताहिक मौसम डाटा के साथ जेमिनी फसल सुरक्षा निर्देश",
    current: "वर्तमान मौसम",
    weeklyForecast: "7-दिन कृषि-पूर्वानुमान",
    gpsLocation: "जीपीएस स्थान का उपयोग करें",
    searchCity: "शहर या क्षेत्र दर्ज करें",
    expertTitle: "कृषि विशेषज्ञ पोर्टल",
    expertSub: "सरकारी कृषि विज्ञान केंद्र (KVK) अधिकारियों या निजी कृषि वैज्ञानिकों से सलाह लें",
    expertList: "आसपास उपलब्ध कृषि वैज्ञानिक",
    scheduleConsult: "मुलाकात निर्धारित करें",
    chatExpert: "विशेषज्ञ से चैट करें",
    callExpert: "ऑडियो/वीडियो कॉल",
    bookingDate: "तारीख चुनें",
    bookingTime: "पसंदीदा समय",
    bookingNotes: "अपनी समस्या का विवरण दें",
    bookButton: "निशुल्क परामर्श बुक करें",
    shopTitle: "आसपास की कृषि दुकानें",
    shopSub: "अपने निकटतम बीज, प्रमाणित खाद, कीटनाशक और नर्सरी की दुकानें खोजें",
    rating: "रेटिंग",
    navigationRoute: "मार्ग मानचित्र दिखाएं",
    contactNo: "दुकान को कॉल करें",
    distanceLabel: "दूरी",
    helpPlaceholder: "उदा: मेरे टमाटर के पत्ते पीले घेरे के साथ भूरे हो रहे हैं, मैं क्या करूँ?"
  },
  kn: {
    tagline: "ನಿಮ್ಮ ಕೃಷಿ ಗೆಳೆಯ",
    langSelector: "ಭಾಷೆ ಆರಿಸಿ",
    cropScan: "ಬೆಳೆ ಸ್ಕ್ಯಾನ್",
    voiceProblem: "ಧ್ವನಿ ಸಮಸ್ಯೆ",
    weather: "ಹವಾಮಾನ",
    experts: "ಕೃಷಿ ತಜ್ಞರು",
    shops: "ಕೃಷಿ ಅಂಗಡಿಗಳು",
    scanHeading: "ಬೆಳೆ ಸಮಸ್ಯೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    scanSub: "ರೋಗಗಳು ಅಥವಾ ಪೋಷಕಾಂಶಗಳ ಕೊರತೆಯನ್ನು ತಕ್ಷಣ ಪತ್ತೆಹಚ್ಚಲು ನಿಮ್ಮ ಬೆಳೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ತೆಗೆಯಿರಿ",
    takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    uploadPhoto: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    sampleDiseases: "ಪರೀಕ್ಷಿಸಲು ಮಾದರಿ ಬೆಳೆ ರೋಗಗಳು",
    analyzing: "ಜೆಮಿನಿ ಎಐ ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    results: "ರೋಗ ಪತ್ತೆ ವರದಿ",
    confidence: "ನಿಖರತೆಯ ಮಟ್ಟ",
    symptoms: "ಕಂಡುಬಂದ ಲಕ್ಷಣಗಳು",
    treatment: "ತಕ್ಷಣದ ಚಿಕಿತ್ಸಾ ಕ್ರಮಗಳು",
    prevention: "ದೀರ್ಘಾವಧಿಯ ತಡೆಗಟ್ಟುವ ಸಲಹೆಗಳು",
    voiceTitle: "ಕೃಷಿ ಸಮಸ್ಯೆಗಳನ್ನು ಧ್ವನಿ ಮೂಲಕ ತಿಳಿಸಿ",
    voiceSub: "ಮೈಕ್ರೊಫೋನ್ ಹಿಡಿದುಕೊಂಡು, ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ಸಮಸ್ಯೆಯನ್ನು ತಿಳಿಸಿ ಮತ್ತು ಆಡಿಯೋ ಉತ್ತರ ಆಲಿಸಿ",
    recordStart: "ರೆಕಾರ್ಡ್ ಮಾಡಲು ಒತ್ತಿ",
    recording: "ರೆಕಾರ್ಡಿಂಗ್ ಆಗುತ್ತಿದೆ... ನಿಲ್ಲಿಸಲು ಮತ್ತೆ ಒತ್ತಿ",
    converting: "ಜೆಮಿನಿ ಮೂಲಕ ಭಾಷಾಂತರ ಮತ್ತು ಪರಿಹಾರ ಚಾಲ್ತಿಯಲ್ಲಿದೆ...",
    playSolution: "ಪರಿಹಾರ ಆಲಿಸಿ",
    orText: "ಅಥವಾ ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಬರೆಯಿರಿ",
    askButton: "ಮಿತ್ರರನ್ನು ಕೇಳಿ",
    weatherTitle: "ಹವಾಮಾನ ಆಧಾರಿತ ಕೃಷಿ ಸಲಹೆಗಳು",
    weatherSub: "ವಾರದ ಹವಾಮಾನ ದತ್ತಾಂಶ ಹಾಗೂ ಜೆಮಿನಿ ಬೆಳೆ ಸಂರಕ್ಷಣೆ ಮಾರ್ಗಸೂಚಿಗಳು",
    current: "ಪ್ರಸ್ತುತ ಹವಾಮಾನ",
    weeklyForecast: "7-ದಿನಗಳ ಕೃಷಿ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    gpsLocation: "ಜಿಪಿಎಸ್ ಬಳಸಿ",
    searchCity: "ಊರು ಅಥವಾ ಜಿಲ್ಲೆ ನಮೂದಿಸಿ",
    expertTitle: "ಕೃಷಿ ತಜ್ಞರ ವೇದಿಕೆ",
    expertSub: "ಸರ್ಕಾರಿ ಕೃಷಿ ವಿಜ್ಞಾನ ಕೇಂದ್ರ (KVK) ಅಧಿಕಾರಿಗಳು ಅಥವಾ ಖಾಸಗಿ ತಜ್ಞರಿಂದ ಸಲಹೆ ಪಡೆಯಿರಿ",
    expertList: "ಸಮೀಪದ ಲಭ್ಯವಿರುವ ಕೃಷಿ ತಜ್ಞರು",
    scheduleConsult: "ಸಲಹಾ ಸಮಯ ಕಾಯ್ದಿರಿಸಿ",
    chatExpert: "ತಜ್ಞರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
    callExpert: "ಆಡಿಯೋ/ವಿಡಿಯೋ ಕರೆ",
    bookingDate: "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
    bookingTime: "ಸಮಯ ಆಯ್ಕೆಮಾಡಿ",
    bookingNotes: "ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ",
    bookButton: "ಉಚಿತ ಸಲಹೆ ಕಾಯ್ದಿರಿಸಿ",
    shopTitle: "ಹತ್ತಿರದ ಕೃಷಿ ಅಂಗಡಿಗಳು",
    shopSub: "ನಿಮ್ಮ ಹತ್ತಿರದ ಬೀಜಗಳು, ಪ್ರಮಾಣೀಕೃತ ರಸಗೊಬ್ಬರಗಳು, ಕೀಟನಾಶಕಗಳು ಮತ್ತು ನರ್ಸರಿಗಳನ್ನು ಪತ್ತೆ ಮಾಡಿ",
    rating: "ರೇಟಿಂಗ್",
    navigationRoute: "ಮಾರ್ಗ ನಕ್ಷೆ ತೋರಿಸಿ",
    contactNo: "ಅಂಗಡಿಗೆ ಕರೆ ಮಾಡಿ",
    distanceLabel: "ದೂರ",
    helpPlaceholder: "ಉದಾ: ನನ್ನ ಟೊಮೆಟೊ ಎಲೆಗಳು ಹಳದಿ ವರ್ತುಲದೊಂದಿಗೆ ಕಂದು ಬಣ್ಣಕ್ಕೆ ತಿರುಗುತ್ತಿವೆ, ಏನು ಮಾಡಬೇಕು?"
  },
  te: {
    tagline: "మీ వ్యవసాయ స్నేహితుడు",
    langSelector: "భాషను ఎంచుకోండి",
    cropScan: "పంట స్కాన్",
    voiceProblem: "వాయిస్ ప్రశ్న",
    weather: "వాతావరణం",
    experts: "వ్యవసాయ నిపుణులు",
    shops: "వ్యవసాయ షాపులు",
    scanHeading: "పంట సమస్యను స్కాన్ చేయండి",
    scanSub: "వ్యాధులు లేదా పోషకాల లోపాలను గుర్తించడానికి పంట ఫోటోను అప్‌లోడ్ చేయండి లేదా తీయండి",
    takePhoto: "ఫోటో తీయండి",
    uploadPhoto: "ఫోటో అప్‌లోడ్",
    sampleDiseases: "పరీక్ష కోసం నమూనా పంట వ్యాధులు",
    analyzing: "జెమిని ఏఐ విశ్లేషిస్తోంది...",
    results: "రోగ నిర్ధారణ నివేదిక",
    confidence: "విశ్వసనీయత స్థాయి",
    symptoms: "గమనించిన లక్షణాలు",
    treatment: "తక్షణ చికిత్సా ప్రణాళిక",
    prevention: "దీర్ఘకాలిక నివారణ సలహా",
    voiceTitle: "వ్యవసాయ సమస్యలను వాయిస్ ద్వారా తెలపండి",
    voiceSub: "మైక్ బటన్ నొక్కి మీ పంట సమస్యను చెప్పండి, సమాధానం వాయిస్ రూపంలో వినండి",
    recordStart: "రికార్డ్ చేయడానికి నొక్కండి",
    recording: "రికార్డింగ్ అవుతోంది... ఆపడానికి మళ్లీ నొక్కండి",
    converting: "జెమిని విశ్లేషించి సమాధానం ఇస్తోంది...",
    playSolution: "సమాధానం వినండి",
    orText: "లేదా మీ సమస్యను టైప్ చేయండి",
    askButton: "మిత్రను అడగండి",
    weatherTitle: "వాతావరణ వ్యవసాయ సలహాలు",
    weatherSub: "వారపు వాతావరణ సమాచారం తో పాటూ జెమిని పంట రక్షణ సూచనలు",
    current: "ప్రస్తుత వాతావరణం",
    weeklyForecast: "7-రోజుల వ్యవసాయ సూచన",
    gpsLocation: "జీపీఎస్ ఉపయోగించండి",
    searchCity: "నగరం లేదా ప్రాంతం",
    expertTitle: "వ్యవసాయ నిపుణుల పోర్టల్",
    expertSub: "కృషి విజ్ఞాన కేంద్రం (KVK) అధికారులు లేదా ప్రైవేట్ వ్యవసాయ శాస్త్రవేత్తలతో సంప్రదించండి",
    expertList: "సమీపంలోని వ్యవసాయ నిపుణులు",
    scheduleConsult: "అపాయింట్‌మెంట్ అడగండి",
    chatExpert: "నిపుణులతో చాట్ చేయండి",
    callExpert: "ఆడియో/వీడియో కాల్",
    bookingDate: "తేదీని ఎంచుకోండి",
    bookingTime: "అనుకూల సమయం",
    bookingNotes: "సమస్యను వివరించండి",
    bookButton: "ఉచిత కన్సల్టేషన్ బుక్ చేయండి",
    shopTitle: "సమీప వ్యవసాయ దుకాణాలు",
    shopSub: "మీకు దగ్గరలోని విత్తనాలు, ధృవీకరించబడిన ఎరువులు, క్రిమిసంహారకాలు మరియు నర్సరీలను కనుగొనండి",
    rating: "రేటింగ్",
    navigationRoute: "మార్గం మ్యాప్ చూపించు",
    contactNo: "షాపుకు కాల్ చేయండి",
    distanceLabel: "దూరం",
    helpPlaceholder: "ఉదా: నా టమోటా ఆకులు పసుపు రంగు అంచులతో గోధుమ రంగులోకి మారుతున్నాయి, ఏం చేయాలి?"
  },
  ta: {
    tagline: "உங்கள் விவசாய நண்பன்",
    langSelector: "மொழியைத் தேர்வுசெய்",
    cropScan: "பயிர் ஸ்கேன்",
    voiceProblem: "குரல் வழி கேள்வி",
    weather: "வானிலை",
    experts: "விவசாய நிபுணர்கள்",
    shops: "விவசாய கடைகள்",
    scanHeading: "பயிர் பிரச்சனையை ஸ்கேன் செய்க",
    scanSub: "நோய்கள் அல்லது ஊட்டச்சத்து குறைபாடுகளை உடனடியாகக் கண்டறிய உங்கள் பயிரின் புகைப்படத்தைப் பதிவேற்றவும் அல்லது எடுக்கவும்",
    takePhoto: "புகைப்படம் எடு",
    uploadPhoto: "புகைப்படம் பதிவேற்று",
    sampleDiseases: "சோதனைக்கான மாதிரி பயிர் நோய்கள்",
    analyzing: "ஜெமினி AI பகுப்பாய்வு செய்கிறது...",
    results: "பயிர் நோய் அறிக்கை",
    confidence: "நம்பகத்தன்மை அளவு",
    symptoms: "கண்டறியப்பட்ட அறிகுறிகள்",
    treatment: "உடனடி சிகிச்சை முறை",
    prevention: "நீண்ட கால தடுப்பு ஆலோசனைகள்",
    voiceTitle: "விவசாய பிரச்சனைகளை குரல் மூலம் கூறவும்",
    voiceSub: "மைக் பொத்தானை அழுத்தி, உங்கள் விவசாயப் பிரச்சனையைத் தெரிவித்து, குரல் வடிவில் தீர்வைக் கேளுங்கள்",
    recordStart: "பதிவு செய்ய அழுத்தவும்",
    recording: "பதிவாகிறது... நிறுத்த மீண்டும் அழுத்தவும்",
    converting: "ஜெமினி மூலம் தீர்வு காணப்படுகிறது...",
    playSolution: "தீர்வை கேட்கவும்",
    orText: "அல்லது உங்கள் பிரச்சனையை எழுதவும்",
    askButton: "மித்ராவிடம் கேளுங்கள்",
    weatherTitle: "வானிலை விவசாய ஆலோசனைகள்",
    weatherSub: "வாராந்திர வானிலை விவரங்களுடன் ஜெமினி பயிர் பாதுகாப்பு வழிகாட்டுதல்கள்",
    current: "தற்போதைய வானிலை",
    weeklyForecast: "7-நாள் விவசாய வானிலை அறிக்கை",
    gpsLocation: "ஜிபிஎஸ் பயன்படுத்தவும்",
    searchCity: "நகரம் அல்லது மாவட்டத்தை உள்ளிடவும்",
    expertTitle: "விவசாய நிபுணர்கள் தளம்",
    expertSub: "அரசு कृषि विज्ञान केंद्र (KVK) அதிகாரிகள் அல்லது தனியார் விவசாய நிபுணர்களிடம் ஆலோசனை பெறுக",
    expertList: "அருகிலுள்ள விவசாய நிபுணர்கள்",
    scheduleConsult: "சந்திப்பை முன்பதிவு செய்க",
    chatExpert: "நிபுணருடன் அரட்டையடிக்க",
    callExpert: "ஆடியோ/வீடியோ அழைப்பு",
    bookingDate: "தேதியைத் தேர்ந்தெடுக்கவும்",
    bookingTime: "விருப்பமான நேரம்",
    bookingNotes: "பிரச்சனையை விவரிக்கவும்",
    bookButton: "இலவச ஆலோசனையை முன்பதிவு செய்க",
    shopTitle: "அருகிலுள்ள விவசாயக் கடைகள்",
    shopSub: "உங்களுக்கு அருகிலுள்ள விதை, சான்றளிக்கப்பட்ட உரங்கள், பூச்சிக்கொல்லி மற்றும் நர்சரிகளைக் கண்டறியவும்",
    rating: "மதிப்பீடு",
    navigationRoute: "வழி வரைபடத்தைக் காட்டு",
    contactNo: "கடைக்கு அழைக்கவும்",
    distanceLabel: "தொலைவு",
    helpPlaceholder: "உதாரணம்: எனது தக்காளி இலைகள் மஞ்சள் வளையங்களுடன் பழுப்பு நிறமாக மாறுகின்றன, நான் என்ன செய்ய வேண்டும்?"
  },
  mr: {
    tagline: "तुमचा शेती मित्र",
    langSelector: "भाषा निवडा",
    cropScan: "पीक स्कॅन",
    voiceProblem: "आवाज प्रश्न",
    weather: "हवामान",
    experts: "कृषी तज्ञ",
    shops: "कृषी दुकाने",
    scanHeading: "पीक समस्या स्कॅन करा",
    scanSub: "रोगांचे किंवा पोषक घटकांच्या कमतरतेचे त्वरित निदान करण्यासाठी पिकाचा फोटो अपलोड करा किंवा काढा",
    takePhoto: "फोटो काढा",
    uploadPhoto: "फोटो अपलोड करा",
    sampleDiseases: "चाचणीसाठी नमुना पीक रोग",
    analyzing: "जेमिनी एआय विश्लेषण करत आहे...",
    results: "निदान अहवाल",
    confidence: "विश्वास पातळी",
    symptoms: "दिसणारी लक्षणे",
    treatment: "तातडीची उपचार योजना",
    prevention: "दीर्घकालीन प्रतिबंधात्मक सल्ला",
    voiceTitle: "तुमची शेती समस्या बोला",
    voiceSub: "माईक बटण दाबा, स्थानिक भाषेत पीक समस्या सांगा आणि उत्तर आवाजात ऐका",
    recordStart: "रेकॉर्डिंगसाठी दाबा",
    recording: "रेकॉर्डिंग सुरू आहे... थांबवण्यासाठी पुन्हा दाबा",
    converting: "जेमिनी विश्लेषण करत आहे...",
    playSolution: "समाधान ऐका",
    orText: "किंवा तुमची समस्या लिहा",
    askButton: "मित्राला विचारा",
    weatherTitle: "हवामान आधारित कृषी सल्ला",
    weatherSub: "साप्ताहिक हवामान अंदाज आणि जेमिनी पीक संरक्षण सूचना",
    current: "सध्याचे हवामान",
    weeklyForecast: "७-दिवसांचा कृषी अंदाज",
    gpsLocation: "जीपीएस वापरा",
    searchCity: "शहर किंवा विभाग टाका",
    expertTitle: "कृषी तज्ञ पोर्टल",
    expertSub: "सरकारी कृषी विज्ञान केंद्र (KVK) अधिकारी किंवा खाजगी कृषी तज्ञांशी चर्चा करा",
    expertList: "नजीकचे उपलब्ध कृषी तज्ञ",
    scheduleConsult: "भेट निश्चित करा",
    chatExpert: "तज्ञांशी चॅट करा",
    callExpert: "ऑडिओ/व्हिडिओ कॉल",
    bookingDate: "तारीख निवडा",
    bookingTime: "वेळ निवडा",
    bookingNotes: "समस्या सांगा",
    bookButton: "मोफत भेट बुक करा",
    shopTitle: "नजीकची कृषी दुकाने",
    shopSub: "तुमच्या जवळचे बियाणे, प्रमाणित खते, कीटकनाशके आणि रोपवाटिका शोधा",
    rating: "रेटिंग",
    navigationRoute: "नक्षा दाखवा",
    contactNo: "दुकानदाराला कॉल करा",
    distanceLabel: "अंतर",
    helpPlaceholder: "उदा: माझ्या टोमॅटोची पाने पिवळ्या कडांसह तपकिरी होत आहेत, मी काय करू?"
  },
  bn: {
    tagline: "আপনার চাষের বন্ধু",
    langSelector: "ভাষা নির্বাচন করুন",
    cropScan: "ফসল স্ক্যান",
    voiceProblem: "ভয়েস সমস্যা",
    weather: "আবহাওয়া",
    experts: "কৃষি বিশেষজ্ঞ",
    shops: "কৃষি দোকান",
    scanHeading: "ফসলের সমস্যা স্ক্যান করুন",
    scanSub: "রোগ বা পুষ্টির অভাব সনাক্ত করতে আপনার ফসলের ছবি আপলোড বা ক্যামেরা ব্যবহার করে তুলুন",
    takePhoto: "ছবি তুলুন",
    uploadPhoto: "ছবি আপলোড করুন",
    sampleDiseases: "পরীক্ষার নমুনা ফসল ও রোগ তালিকা",
    analyzing: "জেমিনি এআই বিশ্লেষণ করছে...",
    results: "রোগ নির্ণয় প্রতিবেদন",
    confidence: "নির্ভরযোগ্যতার মাত্রা",
    symptoms: "পরিলক্ষিত লক্ষণসমূহ",
    treatment: "জরুরী চিকিৎসা পরিকল্পনা",
    prevention: "দীর্ঘমেয়াদী প্রতিরোধ পরামর্শ",
    voiceTitle: "আপনার কৃষি সমস্যা ভয়েসে বলুন",
    voiceSub: "মাইক্রোফোন টিপুন, আপনার নিজের ভাষায় ফসলের রোগ বা সমস্যার কথা বলুন এবং উত্তরটি ভয়েসে শুনুন",
    recordStart: "রেকর্ড করতে স্পর্শ করুন",
    recording: "রেকর্ড হচ্ছে... বন্ধ করতে আবার স্পর্শ করুন",
    converting: "জেমিনি সমাধান খুঁজছে...",
    playSolution: "সমাধান শুনুন",
    orText: "অথবা সমস্যা লিখে পাঠান",
    askButton: "মিত্রকে জিজ্ঞাসা করুন",
    weatherTitle: "আবহাওয়া ভিত্তিক কৃষি পরামর্শ",
    weatherSub: "সাপ্তাহিক আবহাওয়া সম্পর্কিত তথ্যের ওপর জেমিনি ফসল সুরক্ষা নির্দেশিকা",
    current: "বর্তমান আবহাওয়া",
    weeklyForecast: "৭-দিনের কৃষি পূর্বাভাস",
    gpsLocation: "জিপিএস অবস্থান ব্যবহার করুন",
    searchCity: "শহর বা অঞ্চল লিখুন",
    expertTitle: "কৃষি বিশেষজ্ঞ পোর্টাল",
    expertSub: "সরকারী কৃষি বিজ্ঞান কেন্দ্র (KVK) কর্মকর্তা বা সহযোগী কৃষি বিশেষজ্ঞদের পরামর্শ নেন",
    expertList: "নিকটবর্তী কৃষি বিশেষজ্ঞদের তালিকা",
    scheduleConsult: "সাক্ষাতের সময় নির্ধারণ করুন",
    chatExpert: "বিশেষজ্ঞদের সাথে চ্যাট করুন",
    callExpert: "অডিও/ভিডিও কল",
    bookingDate: "তারিখ নির্বাচন করুন",
    bookingTime: "পছন্দের সময়",
    bookingNotes: "আপনার সমস্যার সমস্যাটি বলুন",
    bookButton: "বিনামূল্যে স্লট বুক করুন",
    shopTitle: "নিকটবর্তী কৃষি দোকানসমূহ",
    shopSub: "নিকটবর্তী শংসাপত্র বীজ, সার, কীটনাশক এবং নার্সারি খুঁজুন",
    rating: "রেটিং",
    navigationRoute: "মানচিত্রে রুট দেখুন",
    contactNo: "দোকানে কল করুন",
    distanceLabel: "দূরত্ব",
    helpPlaceholder: "উদাঃ আমার টমেটো গাছের পাতাগুলি বর্ডার হলুদ রঙের সাথে বাদামী হয়ে যাচ্ছে, কি করা উচিত?"
  },
  ml: {
    tagline: "നിങ്ങളുടെ കർഷക സുഹൃത്ത്",
    langSelector: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    cropScan: "വിള സ്കാൻ",
    voiceProblem: "ശബ്ദത്തിലൂടെ ചോദിക്കാം",
    weather: "കാലാവസ്ഥ",
    experts: "കൃഷി വിദഗ്ദ്ധർ",
    shops: "കൃഷി കടകൾ",
    scanHeading: "വിള പ്രശ്നം സ്കാൻ ചെയ്യുക",
    scanSub: "രോഗങ്ങളോ പോഷകക്കുറവോ കണ്ടെത്തുന്നതിന് വിളയുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുകയോ ക്യാമറ ഉപയോഗിച്ച് എടുക്കുകയോ ചെയ്യുക",
    takePhoto: "ഫോട്ടോ എടുക്കുക",
    uploadPhoto: "ഫോട്ടോ അപ്‌ലോഡ്",
    sampleDiseases: "പരീക്ഷണത്തിനുള്ള സാമ്പിൾ വിള രോഗങ്ങൾ",
    analyzing: "ജെമിനി എഐ വിശകലനം ചെയ്യുന്നു...",
    results: "രോഗനിർണ്ണയ റിപ്പോർട്ട്",
    confidence: "വിശ്വാസ്യത നില",
    symptoms: "കണ്ടെത്തിയ രോഗലക്ഷണങ്ങൾ",
    treatment: "ഉടൻ ചെയ്യേണ്ട പ്രതിവിധികൾ",
    prevention: "ഭാവിയിൽ തടയാനുള്ള നിർദ്ദേശങ്ങൾ",
    voiceTitle: "കൃഷി പ്രശ്നങ്ങൾ ശബ്ദത്തിലൂടെ ഉണർത്താം",
    voiceSub: "മൈക്ക് ബട്ടൺ അമർത്തി നിങ്ങളുടെ ഭാഷയിൽ വിള പ്രശ്നം പറയുക, ഉത്തരം വോയിസ് രൂപത്തിൽ കേൾക്കാം",
    recordStart: "റെക്കോർഡ് ചെയ്യാൻ അമർത്തുക",
    recording: "റെക്കോർഡിംഗ് നടക്കുന്നു... നിർത്താൻ വീണ്ടും അമർത്തുക",
    converting: "ജെമിനി ഉത്തരം തയ്യാറാക്കുന്നു...",
    playSolution: "ഉത്തരം കേൾക്കാം",
    orText: "അല്ലെങ്കിൽ നിങ്ങളുടെ പ്രശ്നം എഴുതുക",
    askButton: "മിത്രയോടെ ചോദിക്കാം",
    weatherTitle: "കാലാവസ്ഥാ കൃഷി നിർദ്ദേശങ്ങൾ",
    weatherSub: "വാര്ഷിക കാലാവസ്ഥാ പ്രവചനവും അതിനനുസരിച്ചുള്ള ജെമിനി കൃഷി ഉപദേശങ്ങളും",
    current: "തത്സമയ കാലാവസ്ഥ",
    weeklyForecast: "7-ദിന കൃഷി പ്രവചനം",
    gpsLocation: "ജിപിഎസ് ഉപയോഗിക്കുക",
    searchCity: "നഗരമോ താലൂക്കോ നൽകുക",
    expertTitle: "കൃഷി ശാസ്ത്രജ്ഞരുടെ പോർട്ടൽ",
    expertSub: "സർക്കാർ കൃഷി വിജ്ഞാൻ കേന്ദ്ര (KVK) ഉദ്യോഗസ്ഥരുമായോ കൃഷി വിദഗ്ദ്ധരുമായോ ബന്ധപ്പെടുക",
    expertList: "ലഭ്യമായ കൃഷി വിദഗ്ദ്ധർ",
    scheduleConsult: "കൂടിക്കാഴ്ച നിശ്ചയിക്കുക",
    chatExpert: "വിദഗ്ദ്ധനുമായി ചാറ്റ് ചെയ്യാം",
    callExpert: "ഓഡിയോ/വീഡിയോ കോൾ",
    bookingDate: "തീയതി തിരഞ്ഞെടുക്കുക",
    bookingTime: "അനുയോജ്യമായ സമയം",
    bookingNotes: "പ്രശ്നത്തെക്കുറിച്ച് വിവരണം നൽകുക",
    bookButton: "സൗജന്യ അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക",
    shopTitle: "സമീപത്തെ കൃഷി കടകൾ",
    shopSub: "നിങ്ങൾക്ക് ചുറ്റുമുള്ള വിത്ത്, സാക്ഷ്യപ്പെടുത്തിയ വളങ്ങൾ, കീടനാശിനി കടകൾ, നഴ്സറികൾ എന്നിവ കണ്ടെത്തുക",
    rating: "റേറ്റിംഗ്",
    navigationRoute: "വഴി മാപ്പ് കാണിക്കുക",
    contactNo: "കടയിലേക്ക് വിളിക്കുക",
    distanceLabel: "ദൂരം",
    helpPlaceholder: "ഉദാഹരണം: തക്കാളിയിലകൾ മഞ്ഞ അരികുകളോടെ കരിഞ്ഞു പോകുന്നു, പരിഹാരം എന്താണ്?"
  },
  gu: {
    tagline: "તમારો ખેતી મિત્ર",
    langSelector: "ભાષા પસંદ કરો",
    cropScan: "પાક સ્કેન",
    voiceProblem: "અવાજ પ્રશ્ન",
    weather: "હવામાન",
    experts: "કૃષિ નિષ્ણાતો",
    shops: "કૃષિ દુકાનો",
    scanHeading: "પાક રોગ સ્કેન કરો",
    scanSub: "પાકના રોગો અથવા પોષક તત્વોની ઉણપને ત્વરિત ઓળખવા પાકનો ફોટો અપલોડ કે કેમેરાથી કેપ્ચર કરો",
    takePhoto: "ફોટો લો",
    uploadPhoto: "ફોટો અપલોડ કરો",
    sampleDiseases: "પરીક્ષણ માટે નમૂના પાક રોગો",
    analyzing: "જેમિની એઆઈ વિશ્લેષણ કરે છે...",
    results: "રોગ નિદાન રીપોર્ટ",
    confidence: "વિશ્વાસ સ્તર",
    symptoms: "જોવા મળેલા લક્ષણો",
    treatment: "તાત્કાલિક સારવારના પગલાં",
    prevention: "લાંબા ગાળાના બચાવ પગલાં",
    voiceTitle: "ખેતી સમસ્યાઓ બોલીને જણાવો",
    voiceSub: "માઈક બટન દબાવો, ખેતી સમસ્યા તમારી પ્રાદેશિક ભાષામાં જણાવો અને ઉત્તર ઓડિયોમાં સાંભળો",
    recordStart: "રેકોર્ડિંગ કરવા ક્લિક કરો",
    recording: "રેકોર્ડિંગ શરૂ છે... રોકવા ફરી ક્લિક કરો",
    converting: "જેમિની ઉકેલ શોધી રહ્યું છે...",
    playSolution: "ઉકેલ ઓડિયોમાં સાંભળો",
    orText: "અથવા પ્રશ્ન લખીને મોકલો",
    askButton: "મિત્રને પૂછો",
    weatherTitle: "હવામાન કૃષિ સલાહ",
    weatherSub: "સાપ્તાહિક નીતિઓની માહિતી સાથે જેમીની આધારિત વાવણી સલાહ",
    current: "વર્તમાન હવામાન",
    weeklyForecast: "૭-દિવસીય કૃષિ પૂર્વાનુમાન",
    gpsLocation: "જીપીએસ વાપરો",
    searchCity: "શહેર અથવા જિલ્લો દાખલ કરો",
    expertTitle: "કૃષિ સલાહકાર કેન્દ્ર",
    expertSub: "સરકારી કૃષિ વિજ્ઞાન કેન્દ્ર (KVK) અધિકારીઓ અથવા ખાનગી કૃષિ વૈજ્ઞાનિકોનો સંપર્ક કરો",
    expertList: "નજીકના ઉપલબ્ધ કૃષિ તજજ્ઞો",
    scheduleConsult: "મુલાકાતનો સમય મળો",
    chatExpert: "નિષ્ણાત સાથે વાતચીત કરો",
    callExpert: "ઓડિયો/વીડિયો કોલ",
    bookingDate: "તારીખ પસંદ કરો",
    bookingTime: "પસંદગીનો સમય",
    bookingNotes: "સમસ્યાની વિગત આપો",
    bookButton: "નિઃશુલ્ક મુલાકાત બુક કરો",
    shopTitle: "નજીકની કૃષિ દુકાનો",
    shopSub: "પ્રમાણિત બિયારણ, ખાતર, જંતુનાશક દવાઓ અને નર્સરીની માહિતી મેળવો",
    rating: "રેટિંગ",
    navigationRoute: "નકશો બતાવો",
    contactNo: "દુકાનદારને કોલ કરો",
    distanceLabel: "અંતર",
    helpPlaceholder: "દા.ત. મારા ટામેટાના પાંદડા પીળી બોર્ડર સાથે કથ્થઈ પડી રહ્યા છે, મારે શું કરવું?"
  },
  pa: {
    tagline: "ਤੁਹਾਡਾ ਖੇਤੀ ਮਿੱਤਰ",
    langSelector: "ਭਾਸ਼ਾ ਚੁਣੋ",
    cropScan: "ਫ਼ਸਲ ਸਕੈਨ",
    voiceProblem: "ਆਵਾਜ਼ ਰਾਹੀਂ ਪੁੱਛੋ",
    weather: "ਮੌਸਮ",
    experts: "ਖੇਤੀ ਮਾਹਰ",
    shops: "ਖੇਤੀ ਦੁਕਾਨਾਂ",
    scanHeading: "ਫ਼ਸਲ ਦੀ ਸਮੱਸਿਆ ਸਕੈਨ ਕਰੋ",
    scanSub: "ਬੀਮਾਰੀਆਂ ਜਾਂ ਪੋਸ਼ਕ ਤੱਤਾਂ ਦੀ ਕਮੀ ਦੀ ਤੁਰੰਤ ਪਛਾਣ ਕਰਨ ਲਈ ਫ਼ਸਲ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ ਜਾਂ ਖਿੱਚੋ",
    takePhoto: "ਫੋਟੋ ਖਿੱਚੋ",
    uploadPhoto: "ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    sampleDiseases: "ਟੈਸਟਿੰਗ ਲਈ ਨਮੂਨਾ ਫ਼ਸਲ ਬੀਮਾਰੀਆਂ",
    analyzing: "ਜੈਮਿਨੀ ਏਆਈ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...",
    results: "ਨਿਦਾਨ ਰਿਪੋਰਟ",
    confidence: "ਭਰੋਸਾ ਪੱਧਰ",
    symptoms: "ਵੇਖੇ ਗਏ ਲੱਛਣ",
    treatment: "ਤੁਰੰਤ ਇਲਾਜ ਯੋਜਨਾ",
    prevention: "ਦੀਰਘਕਾਲੀ ਰੋਕਥਾਮ ਸਲਾਹ",
    voiceTitle: "ਖੇਤੀ ਸਮੱਸਿਆਵਾਂ ਬੋਲ ਕੇ ਦੱਸੋ",
    voiceSub: "ਮਾਈਕ ਬਟਨ ਦਬਾਓ, ਆਪਣੀ ਖੇਤਰੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਮੱਸਿਆ ਬੋਲੋ ਅਤੇ ਸਮਾਧਾਨ ਆਵਾਜ਼ ਰਾਹੀਂ ਸੁਣੋ",
    recordStart: "ਰਿਕਾਰਡ ਕਰਨ ਲਈ ਦਬਾਓ",
    recording: "ਰਿਕਾਰਡਿੰਗ ਹੋ ਰਹੀ ਹੈ... ਰੋਕਣ ਲਈ ਫਿਰ ਦਬਾਓ",
    converting: "ਜੈਮਿਨੀ ਹੱਲ ਲੱਭ ਰਿਹਾ ਹੈ...",
    playSolution: "ਸਮਾਧਾਨ ਸੁਣੋ",
    orText: "ਜਾਂ ਆਪਣੀ ਸਮੱਸਿਆ ਲਿਖੋ",
    askButton: "ਮਿੱਤਰ ਨੂੰ ਪੁੱਛੋ",
    weatherTitle: "ਮੌਸਮ ਆਧਾਰਿਤ ਖੇਤੀ ਸਲਾਹ",
    weatherSub: "ਹਫ਼ਤਾਵਾਰੀ ਮੌਸਮ ਅਪਡੇਟ ਅਤੇ ਜੈਮਿਨੀ ਫ਼ਸਲ ਸੁਰੱਖਿਆ ਨਿਰਦੇਸ਼",
    current: "ਮੌਜੂਦਾ ਮੌਸਮ",
    weeklyForecast: "7-ਦਿਨ ਖੇਤੀ ਪੂਰਵ-ਅਨੁਮਾਨ",
    gpsLocation: "ਜੀਪੀਐਸ ਵਰਤੋਂ",
    searchCity: "ਸ਼ਹਿਰ ਜਾਂ ਖੇਤਰ ਭਰੋ",
    expertTitle: "ਖੇਤੀਬਾੜੀ ਮਾਹਰ ਪੋਰਟਲ",
    expertSub: "ਸਰਕਾਰੀ ਕ੍ਰਿਸ਼ੀ ਵਿਗਿਆਨ ਕੇਂਦਰ (KVK) ਅਫਸਰਾਂ ਜਾਂ ਨਿੱਜੀ ਖੇਤੀ ਵਿਗਿਆਨੀਆਂ ਨਾਲ ਸਲਾਹ ਕਰੋ",
    expertList: "ਨੇੜਲੇ ਉਪਲਬਧ ਖੇਤੀ ਮਾਹਰ",
    scheduleConsult: "ਮੁਲਾਕਾਤ ਤੈਅ ਕਰੋ",
    chatExpert: "ਮਾਹਰ ਨਾਲ ਚੈਟ ਕਰੋ",
    callExpert: "ਆਡੀਓ/ਵੀਡੀਓ ਕਾਲ",
    bookingDate: "ਤਾਰੀਖ ਚੁਣੋ",
    bookingTime: "ਸਮਾਂ ਚੋਣ",
    bookingNotes: "ਸਮੱਸਿਆ ਦਾ ਵੇਰਵਾ ਦਿਓ",
    bookButton: "ਮੁਫ਼ਤ ਸਲਾਹ ਬੁੱਕ ਕਰੋ",
    shopTitle: "ਨੇੜਲੀਆਂ ਖੇਤੀ ਦੁਕਾਨਾਂ",
    shopSub: "ਆਪਣੇ ਨੇੜੇ ਬੀਜ, ਪ੍ਰਮਾਣਿਤ ਖਾਦ, ਕੀਟਨਾਸ਼ਕ ਅਤੇ ਨਰਸਰੀਆਂ ਲੱਭੋ",
    rating: "ਰੇਟਿੰਗ",
    navigationRoute: "ਰੂਟ ਮੈਪ ਵੇਖੋ",
    contactNo: "ਦੁਕਾਨ ਨੂੰ ਕਾਲ ਕਰੋ",
    distanceLabel: "ਦੂਰੀ",
    helpPlaceholder: "ਉਦਾਹਰਨ: ਮੇਰੇ ਟਮਾਟਰ ਦੇ ਪੱਤੇ ਪੀਲੇ ਘੇਰਿਆਂ ਨਾਲ ਭੂਰੇ ਹੋ ਰਹੇ ਹਨ, ਕੀ ਕਰਾਂ?"
  }
};
